kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.1-0`:
```
* homogenised all version strings to 1.0.0
* various install targets added that were missing
* Enable selection of PCL people detector in example launch files.
Usage example added to the README file.
* Fix vertical flip of RGB images in PCL people detector (hope this works in all cases/sensor setups)
* Add missing OpenCV 2 dependencies
* Fix rosdep issue due to typo
* Compiling on kinetic. Rviz crashes with views (QT bug?)
* Adding launch file for …
```

spencer_people_tracking: 1.0.1-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.2-0`:
- previous version for package: `1.0.1-0`
- No changes
```
* added missing roslib deps
```
```
* added missing roslib deps
```
```
* added missing roslib deps
```
```
* added missing roslib deps
```
```
* added missing roslib deps
```
```
* added missing roslib deps
```
- No changes
```
* added missing roslib deps …
```

spencer_people_tracking: 1.0.2-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.3-0`:
- previous version for package: `1.0.2-0`
```
* added visualisation_msgs dep
```
- No changes
- No changes
- No changes
- No changes
```
* moved tf_filter
* added nav_msgs and install targets
```
- No changes
- No changes
- No changes
- No changes
```
* added tf dep
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* added install targets
* added eigen dep …
```

spencer_people_tracking: 1.0.3-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.1-0`:
```
* Added missing install files.
* Adding install files.
* Initial version.
```
```
* Updated install section to add launch files, primitives etc.
* Updated the installation instuctions, added a few examples to run.
* Initial version.
```
```
* Initial version.
```
```
* Fixed install params.
* Added visualization_msgs dep.
* Initial version.
* …
```

oru_navigation: 0.0.1-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

indigo/iliad-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.1-0`:
- distro file: `indigo/iliad-dist.yaml`
```
* Added missing install files.
* Adding install files.
* Initial version.
```
```
* Updated install section to add launch files, primitives etc.
* Updated the installation instuctions, added a few examples to run.
* Initial version.
```
```
* Initial version.
```
```
* Fixed install params.
* Added visualization_msgs dep.
* Initial version.
* …
```

oru_navigation: 0.0.1-0 in 'indigo/iliad-dist.yaml' [bloom]

---

kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.2-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fixed dependencies.
```
- No changes
- No changes
```
* Fixed dependencies.
```
- No changes
``` …
```

oru_navigation: 0.0.2-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.5-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Updated dependencies.
* Fixed type_id factory to get the right geometry model of the robot.
```
``` …
```

oru_navigation: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.7-0`:
- upstream repository: https://github.com/LCAS/spencer_people_tracking.git
- previous version for package: `1.0.5-0`
- No changes
- No changes
- No changes
- No changes
```
* Add missing install targets
```
- No changes
- No changes
```
* Add missing install targets
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* corrected version
* Adding metapackage spencer_people_tracking_full
* Contributors: Marc Hanheide, Timm Linder
* corrected version
* Adding metapackage …
```

spencer_people_tracking: 1.0.7-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `fremen` to `0.3.1-0`:
- upstream repository: https://github.com/strands-project/fremen.git
- release repository: https://github.com/strands-project-releases/fremen.git
- No changes
- No changes
- No changes
```
* Frongo Web Improvements for Anomalies and Anomalies fixed in frongo (#43 <https://github.com/strands-project/fremen/issues/43>)
* fingers crossed this is a hail mary (was #42 <https://github.com/strands-project/fremen/issues/42>)
* fixing stupid error
* handling empty lists
* first version with anomalies
* ok, kind of working now
```
- No changes
```
* Event modelling (#45 …
```

fremen: 0.3.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

added perception_oru-private and velodyne drivers. To add proper tags and release packages.

adding source tags

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.2.1-0`:
```
* Merge pull request #3 <https://github.com/OrebroUniversity/navigation_oru-release/issues/3> from batman177/master
Add LS2000 laser scanner to ILIAD cititruck etc.
* Add LS2000 laser scanner; update Rviz config; fix robot initial position
* merge
* Merge branch 'master' of github.com:OrebroUniversity/navigation_oru-release
* decreased frequency for odometry
* …
```

oru_navigation: 0.2.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.2.1-2`:
- previous version for package: `0.2.1-0`
```
* Merge pull request #3 <https://github.com/OrebroUniversity/navigation_oru-release/issues/3> from batman177/master
Add LS2000 laser scanner to ILIAD cititruck etc.
* Add LS2000 laser scanner; update Rviz config; fix robot initial position
* merge
* Merge branch 'master' of github.com:OrebroUniversity/navigation_oru-release
* decreased frequency for odometry
* …
```

oru_navigation: 0.2.1-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.2.2-0`:
- bloom version: `0.6.1`
- previous version for package: `0.2.1-2`
```
* Made the navigation laser and safety laser to have the same FOV to get the raytracing to work correctly (using ray_gpu + a NVIDIA card).
* Added rviz cfg for ncfm example with three trucks
* Add Kinect v2 simulation. In iliad_single_truck.launch, add options for enabling/disabling simulation of Kinect v1, v2 and Velodyne sensors.
* Updated DEPENDS and CATKIN_DEPENDS.
* showing the costmap_2D visualization, adding the possibility to read the …
```

oru_navigation: 0.2.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.0.2-0`:
```
* added install stuff
* added tf prefix
```
```
* Merge pull request #20 <https://github.com/LCAS/Thorvald/issues/20> from Jailander/kinetic-devel
Adding Safety stop service
* changed license to TODO
* added install stuff
* added tf prefix
* re-respecting coding guidelines
* respecting original coding style
* Adding Safety stop service
* Contributors: Jaime Pulido Fentanes, Marc Hanheide, larsgrim
```
```
* added install stuff
* added caster wheels to …
```

thorvald: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `steering_functions` to `1.0.1-0`:
- upstream repository: https://github.com/iliad-project/steering_functions.git
- release repository: https://github.com/lcas-releases/steering_functions.git
```
* changed maintainer for iliad branch
* Fixed formating in README
Signed-off-by: Holger Banzhaf <mailto:holger.banzhaf@de.bosch.com>
* Updated README
Signed-off-by: Holger Banzhaf <mailto:holger.banzhaf@de.bosch.com>
* Renamed HC into HC_RS
Signed-off-by: Holger Banzhaf <mailto:holger.banzhaf@de.bosch.com>
* Renamed CC_Reeds_Shepp_State_Space into CC00_Reeds_Shepp_State_Space
Signed-off-by: Holger Banzhaf <mailto:holger.banzhaf@de.bosch.com>
* …
```

steering_functions: 1.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Still missing releases for repository libfreenect2

moved libfreenect to its repo

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.3.0-0`:
```
* post IJCAI demo, added some maps and launch files for arena
* IJCAI demo map
* Fixed the last launch example with the pallet picking.
* Getting single_truck.launch from the tutorial to run again.
* Merge pull request #25 <https://github.com/OrebroUniversity/navigation_oru-release/issues/25> from batman177/master
Rough extrinsic calibration (sensors against each other) of Velodyne, Asus, Kinect v2, 2D lasers
* Extrinsic calibration of Asus on …
```

oru_navigation: 0.3.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.4.0-0`:
- previous version for package: `0.3.0-0`
```
* Merge pull request #27 <https://github.com/OrebroUniversity/navigation_oru-release/issues/27> from batman177/master
Cititruck calibration
* Merge branch 'master' into master
* Merge pull request #28 <https://github.com/OrebroUniversity/navigation_oru-release/issues/28> from MFernandezCarmona/master
Working version in NCFM cititruck4
* error in velodyne tf
* …
```

oru_navigation: 0.4.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.0.0-0`:
- previous version for package: `0.2.3-0`
```
* Merge branch 'kinetic-devel' of http://www.github.com/LCAS/Thorvald into kinetic-devel
```
```
* Merge branch 'kinetic-devel' of http://www.github.com/LCAS/Thorvald into kinetic-devel
```
```
* Merge pull request #65 <https://github.com/LCAS/Thorvald/issues/65> from larsgrim/kinetic-devel
Structural changes
* thorvald_model renamed to thorvald_description
* Merge branch 'kinetic-devel' of http://www.github.com/LCAS/Thorvald into …
```

thorvald: 1.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.0.2-0`:
- previous version for package: `1.0.0-0`
```
* Merge pull request #66 <https://github.com/LCAS/Thorvald/issues/66> from gpdas/rm_model_dep
merging this. dep updates in thorvald_bringup. thorvald_model -> thorvald_description
* some more thorvald_model references corrected
removed sensor_frames_lincoln_velo_k2.xacro
* Contributors: Gautham P Das, gpdas
```
- No changes
- No changes
```
* Merge pull request #66 <https://github.com/LCAS/Thorvald/issues/66> from gpdas/rm_model_dep
merging this. dep updates in thorvald_bringup. …
```

thorvald: 1.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.0.2-1`:
- previous version for package: `1.0.2-0`
```
* Merge pull request #66 <https://github.com/LCAS/Thorvald/issues/66> from gpdas/rm_model_dep
merging this. dep updates in thorvald_bringup. thorvald_model -> thorvald_description
* some more thorvald_model references corrected
removed sensor_frames_lincoln_velo_k2.xacro
* Contributors: Gautham P Das, gpdas
```
- No changes
- No changes
```
* Merge pull request #66 <https://github.com/LCAS/Thorvald/issues/66> from gpdas/rm_model_dep
merging this. dep updates in thorvald_bringup. …
```

thorvald: 1.0.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ouster` to `0.1.1-0`:
```
* Removing ouster_viz (#2 <https://github.com/LCAS/ouster_example/issues/2>)
* Removing ouster_viz
* Remove dependencies on ouster_viz
* Fix CMakelist of ouster_client
* Typo in CMakelist
* Remove visualization example code and Fix timestamp problem
* Fix tf2 error in build
* Added tf2_geometry_msgs in CMakelist and package.xml
* Fix header dependencies
* Update CMakefile
* Install target for include (ouster_client)
* Merge pull request #1 …
```

ouster: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.2.0-1`:
- previous version for package: `1.1.3-1`
```
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into marcs_sync_sim
```
```
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into marcs_sync_sim
```
```
* Merge pull request #83 <https://github.com/LCAS/Thorvald/issues/83> from LCAS/marcs_sync_sim
Proper Simulation
* Passes through Gazebo odometry should it be published.
This can be turned off setting passthrough_gazebo_odometry to false. …
```

thorvald: 1.2.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `fremen` to `0.3.1-1`:
- upstream repository: https://github.com/strands-project/fremen.git
- release repository: https://github.com/strands-project-releases/fremen.git
- No changes
- No changes
- No changes
```
* Frongo Web Improvements for Anomalies and Anomalies fixed in frongo (#43 <https://github.com/strands-project/fremen/issues/43>)
* fingers crossed this is a hail mary (was #42 <https://github.com/strands-project/fremen/issues/42>)
* fixing stupid error
* handling empty lists
* first version with anomalies
* ok, kind of working now
```
- No changes
```
* Event modelling (#45 …
```

fremen: 0.3.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_gazebo_plugin` to `0.0.1-1`:
- upstream repository: https://github.com/LCAS/realsense_gazebo_plugin.git
- release repository: https://github.com/lcas-releases/realsense_gazebo_plugin.git
```
* Fixed dependencies missing in package.xml
* Updated maintainer and install target
* Merge pull request #39 <https://github.com/LCAS/realsense_gazebo_plugin/issues/39> from ManMan88/master
fix issue #37 <https://github.com/LCAS/realsense_gazebo_plugin/issues/37>
* Merge pull request #45 <https://github.com/LCAS/realsense_gazebo_plugin/issues/45> from Awesome-Technologies/gazebo-compat
Keep compatibility with earlier Gazebo …
```

realsense_gazebo_plugin: 0.0.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.3.1-1`:
- previous version for package: `1.3.0-1`
```
* melodic-1.3.0
* changelog
```
```
* melodic-1.3.0
* changelog
```
```
* melodic-1.3.0
* changelog
```
```
* melodic-1.3.0
* changelog
* changed gazebo for melodic
```
```
* melodic-1.3.0
* changelog
```
```
* add datum file argument for GPS sim and future georeferenced simulations
* melodic-1.3.0
* changelog
* changed gazebo …
```

thorvald: 1.3.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.3.2-1`:
- previous version for package: `1.3.1-1`
```
* melodic-1.3.1
* changelogs
* melodic-1.3.0
* changelog
```
```
* Merge pull request #111 <https://github.com/SAGARobotics/Thorvald/issues/111> from MikHut/melodic-devel
tf_prefix fix same as #109 <https://github.com/SAGARobotics/Thorvald/issues/109> but for melodic-devel
* merge conflicts
* melodic-1.3.1
* changelogs
* melodic-1.3.0
* changelog
* Contributors: Jaime Pulido Fentanes, Marc Hanheide, c-small
```
```
* Merge pull request #111 …
```

thorvald: 1.3.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.2.0-1`:
- upstream repository: https://github.com/spencer-project/spencer_people_tracking.git
```
* Merge branch 'master' into melodic
* Fixes required for ROS Melodic support
- OpenCV2 to 3 migration
```
```
* Merge branch 'master' into melodic
* Fixes required for ROS Melodic support
```
```
* Merge branch 'master' into melodic
```
```
* Merge branch 'master' into melodic
```
```
* Merge branch 'master' into melodic …
```

spencer_people_tracking: 1.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `2.1.1-1`:
- previous version for package: `2.1.0-1`
```
* Merge branch 'melodic-devel' into urdfs
* Merge branch 'melodic-devel' into omni-fix
* Contributors: Michael Hutchinson
```
```
* Merge branch 'melodic-devel' into urdfs
* Merge branch 'melodic-devel' into omni-fix
* Contributors: Michael Hutchinson
```
```
* Merge pull request #162 <https://github.com/magnucha/Thorvald/issues/162> from magnucha/fix-compiler-warnings
Remove -Wnarrowing compiler warnings
* Implement cleaner fix as tested on thorvald-055
* Merge branch …
```

thorvald: 2.1.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.2.0-1`:
- previous version for package: `0.1.1-1`
```
* remove default pole likelihood field
* Merge pull request #48 <https://github.com/SAGARobotics/AgriNav/issues/48> from adambinch/melodic-devel
Pole Localisation
* Merge branch 'master' of https://github.com/SAGARobotics/AgriNav into melodic-devel
* Merge pull request #53 <https://github.com/SAGARobotics/AgriNav/issues/53> from adambinch/closest_edges
row trav determines closest edge from toponav 2 topic /closest_edges
* fix
* fixes
* backwards compatible
* row …
```

saga_agrinav: 0.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

rosdep/lcas.yaml

There is still an error looking for a robotnik libraries

Robotnik lib

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.1.8-1`:
- previous version for package: `0.1.1-1`
```
* Add much faster method of session filtering
* Update default requirements
* Bump version
* Support for backwards bytes in py2/3
* basestring in py3 compat patch
* Hacky fix to ensure ROS builds contain the meta
* Enable uploads
* Add dist and wheel packaging and util script to release on PYPI
* Version increment for PyPi dist
* Ensure package data is respected in python lib
* Merge pull request #22 <https://github.com/RaymondKirk/topic_store/issues/22> from …
```

topic_store: 0.1.8-1 in 'melodic/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Please add the following dependency to the rosdep database.
TODO
TODO link to source repository
TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.
Distro packaging links:
- Debian: https://packages.debian.org/
- REQUIRED
- Ubuntu: https://packages.ubuntu.com/
- REQUIRED
- Fedora: https://packages.fedoraproject.org/
- IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
- IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
- IF AVAILABLE
- macOS: https://formulae.brew.sh/
- IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
- IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
- OPTIONAL
- openSUSE: https://software.opensuse.org/package/
- IF AVAILABLE
- rhel: https://rhel.pkgs.org/
- …

added livox

---

.github/workflows/build_cache.yaml

add PR cache test

---

.github/workflows/build_cache.yaml

no need for token

---

humble/lcas-dist.yaml

Adding aoc_strawberry_scenario to our humble packages

Update lcas-dist.yaml - adding aoc_strawberry_scenario

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `hunter_robot` to `0.0.1-1`:
- upstream repository: https://github.com/LCAS/hunter_robot.git
- release repository: https://github.com/lcas-releases/hunter_robot.git
- bloom version: `0.12.0`
```
* Merge pull request #9 <https://github.com/LCAS/hunter_robot/issues/9> from hariharan20/main
Tf fix and package.xml update
* package.xml update
* removed controller and fix tf
* Merge pull request #6 <https://github.com/LCAS/hunter_robot/issues/6> from PabloEspejeLS/main
adding hunter robot package
* adding hunter robot package
* Merge pull request #2 <https://github.com/LCAS/hunter_robot/issues/2> from PabloEspejeLS/main
First Commit
* First Commit
* Contributors: Geesara …
```

hunter_robot: 0.0.1-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Adding teach and repeat to our humble distro

Update lcas-dist.yaml - adding teach and repeat repo

---

humble/lcas-dist.yaml

first attempt to isolate packages from the navigation stack

Update lcas-dist.yaml - adding aoc_robot_boundary_checker
