kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.4-0`:
- previous version for package: `1.0.3-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* missing nav_msgs
```
- No changes
- No changes
- No changes
- No changes
```
* added angles dep
```
- No changes
- No changes …

spencer_people_tracking: 1.0.4-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.5-0`:
- previous version for package: `1.0.4-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'master' of https://github.com/lcas/spencer_people_tracking
* added …
```

spencer_people_tracking: 1.0.5-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

kinetic/iliad-dist.yaml

Increasing version of package(s) in repository `acado` to `1.2.3-0`:
- upstream repository: https://github.com/LCAS/acado.git
- release repository: https://github.com/LCAS/acado_release.git
```
* added missing package.xml
* Merge pull request #161 <https://github.com/LCAS/acado/issues/161> from clearpathrobotics/CORE-1683_spam_fix
Commented out a message that gets displayed even when PRINTLEVEL is set to NONE
* minor update lifted adjoint integrator
* correction of the adjoint term
* removed the option LIFTED_INTEGRATOR_MODE
* implemented INIS scheme with adjoint correction
* adjoint exact Hessian solver
* fixed bug regarding gradient update in exact Hessian RTI
* adjoint gradient …
```

acado: 1.2.3-0 in 'kinetic/iliad-dist.yaml' [bloom]

---

indigo/iliad-dist.yaml

Increasing version of package(s) in repository `acado` to `1.2.3-0`:
- upstream repository: https://github.com/LCAS/acado.git
- release repository: https://github.com/LCAS/acado_release.git
- distro file: `indigo/iliad-dist.yaml`
```
* added missing package.xml
* Merge pull request #161 <https://github.com/LCAS/acado/issues/161> from clearpathrobotics/CORE-1683_spam_fix
Commented out a message that gets displayed even when PRINTLEVEL is set to NONE
* minor update lifted adjoint integrator
* correction of the adjoint term
* removed the option LIFTED_INTEGRATOR_MODE
* implemented INIS scheme with adjoint correction
* adjoint exact Hessian solver
* fixed bug regarding gradient update in exact Hessian RTI
* adjoint gradient …
```

acado: 1.2.3-0 in 'indigo/iliad-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sandbox` to `0.0.5-0`:
- upstream repository: https://github.com/LCAS/sandbox.git
- release repository: https://github.com/LCAS/sandbox-release.git
- No changes

sandbox: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.6-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Added missing packages in the meta package.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No …

oru_navigation: 0.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.5-0`:
- upstream repository: https://github.com/LCAS/spencer_people_tracking.git
- previous version for package: `1.0.5-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'master' of https://github.com/lcas/spencer_people_tracking
* …
```

spencer_people_tracking: 1.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.9-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

oru_navigation: 0.0.9-0 in 'indigo/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.0.10-0`:
- previous version for package: `0.0.9-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Found race condistion.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix to get it to build on binaries for …
```

oru_navigation: 0.0.10-0 in 'indigo/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.0.8-0`:
```
* added cv_bridge to catkin build (#18 <https://github.com/LCAS/bayestracking/issues/18>)
* Tracking NN including labels (#13 <https://github.com/LCAS/bayestracking/issues/13>)
* Tracking NN including labels
without auto formatting
* Implimented NN_LABELED
Restored default behaviour implimented another association algorithm
* Included NN_LABEL in Association Matrix
* correct mistyped word
* NNJPDA_LABEL implimented
* Added seq_size and seq_time …
```

bayes_tracking: 1.0.8-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.0.8-0`:
```
* added cv_bridge to catkin build (#18 <https://github.com/LCAS/bayestracking/issues/18>)
* Tracking NN including labels (#13 <https://github.com/LCAS/bayestracking/issues/13>)
* Tracking NN including labels
without auto formatting
* Implimented NN_LABELED
Restored default behaviour implimented another association algorithm
* Included NN_LABEL in Association Matrix
* correct mistyped word
* NNJPDA_LABEL implimented
* Added seq_size and seq_time …
```

bayes_tracking: 1.0.8-0 in 'indigo/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.1.1-0`:
- previous version for package: `0.0.6-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

oru_navigation: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.0.2-0`:
- No changes

iliad_distribution: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.1.2-0`:
- previous version for package: `0.0.10-0`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Revert "changed to gazebo8"
This reverts commit 3ab9b3f35bdabdff87abd911a6b9f208883179e9.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Revert "changed to gazebo8"
This reverts commit 3ab9b3f35bdabdff87abd911a6b9f208883179e9. …
```

oru_navigation: 0.1.2-0 in 'indigo/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `turtlebot_apps` to `2.3.9-0`:
- upstream repository: https://github.com/lcas/turtlebot_apps.git
- release repository: https://github.com/lcas-releases/turtlebot_apps.git

turtlebot_apps: 2.3.9-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `turtlebot_simulator` to `2.2.3-0`:
- upstream repository: https://github.com/lcas/turtlebot_simulator.git
- release repository: https://github.com/lcas-releases/turtlebot_simulator.git
```
* fixed maintainers
* prepared for name spaces
* fixing indention
* Update amcl_demo.launch
* remove backup files
* Fix changing amcl.launch.xml and gmapping.launch.xml locations under turtlebot_navigation
* Contributors: Marc Hanheide, Mohamed Al Zaiady, Mohamed Elzaiady, Tully Foote, mzaiady
```
```
* fixed maintainers
```
```
* fixed maintainers
* Fixed amcl include path
Fixed include path for …
```

turtlebot_simulator: 2.2.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `0.1.18-0`:
- previous version for package: `0.1.17-0`
- No changes
- No changes
- No changes
```
* changed to new kinetic launch style
```

lcas_teaching: 0.1.18-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_common` to `0.1.12-0`:
- upstream repository: https://github.com/strands-project/scitos_common.git
- release repository: https://github.com/strands-project-releases/scitos_common.git
- No changes
- No changes
- No changes

scitos_common: 0.1.12-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sicks300` to `1.0.6-0`:
- upstream repository: https://github.com/strands-project/sicks300.git
- release repository: https://github.com/strands-project-releases/sicks300.git
```
* removed external maintainer
```

sicks300: 1.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mongodb_store` to `0.2.2-0`:
```
* fixed wrong install place
```
- No changes
- No changes
- No changes

mongodb_store: 0.2.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_drivers` to `0.2.0-0`:
- upstream repository: https://github.com/strands-project/scitos_drivers.git
- release repository: https://github.com/strands-project-releases/scitos_drivers.git
```
* changelogs
* changed maintainer from Chris to Marc
* changed maintainer from Chris to Marc
```
```
* removed odometry_mileage as it caused a cyclic dependency
* changelogs
```
```
* changelogs
* changed maintainer from Chris to Marc
* changed maintainer from Chris to Marc
```
```
* added qt4 dep
* …
```

scitos_drivers: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_apps` to `0.1.1-0`:
- upstream repository: https://github.com/strands-project/scitos_apps.git
- release repository: https://github.com/strands-project-releases/scitos_apps.git
- No changes
- No changes
- No changes
- No changes
```
* Merge pull request #157 <https://github.com/strands-project/scitos_apps/issues/157> from gestom/hydro-devel
Docking ends up in a 'safe' position
* Docking end up far away from station in the case of a timeout
* Safe timeout
* Contributors: Christian Dondrup, Nick Hawes, Tom Krajnik
```
- No changes
- No changes
- No changes

scitos_apps: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_apps` to `0.1.2-0`:
- upstream repository: https://github.com/strands-project/scitos_apps.git
- release repository: https://github.com/strands-project-releases/scitos_apps.git
- No changes
- No changes
- No changes
- No changes
```
* added missing opencv dependency
```
- No changes
- No changes
- No changes

scitos_apps: 0.1.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_movebase` to `0.0.23-0`:
- upstream repository: https://github.com/strands-project/strands_movebase.git
- release repository: https://github.com/strands-project-releases/strands_movebase.git
- No changes
- No changes
- No changes
- No changes
```
* Added proper install target for subsampling nodelet
* Contributors: Nils Bore
```
- No changes

strands_movebase: 0.0.23-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_webtools` to `0.1.0-0`:
- upstream repository: https://github.com/strands-project/strands_webtools.git
- release repository: https://github.com/strands-project-releases/strands_webtools.git
```
* changed mjpeg_server to web_video_server
```

strands_webtools: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `twitter_bootstrap` to `0.0.3-0`:
- upstream repository: https://github.com/strands-project/twitter_bootstrap.git
- release repository: https://github.com/strands-project-releases/twitter_bootstrap.git

twitter_bootstrap: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_ui` to `0.1.0-0`:
- upstream repository: https://github.com/strands-project/strands_ui.git
- release repository: https://github.com/strands-project-releases/strands_ui.git
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_ui: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_apps` to `0.2.6-0`:
- upstream repository: https://github.com/strands-project/strands_apps.git
- release repository: https://github.com/strands-project-releases/strands_apps.git
```
* always check door before passing
* display arrow while waiting
* updates to use door waiting properly
* reduce required time of seeing the door open for the glass door.
* less confident on open doors when doing door_wait_and_move_base as this action is to be used for glass doors
* Fixing bug when no doors in the environment (#64 <https://github.com/strands-project/strands_apps/issues/64>)
* adding door prediction to install targets
* fixing bug when …
```

strands_apps: 0.2.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `openni_wrapper` to `0.0.11-0`:
- upstream repository: https://github.com/strands-project/openni_wrapper.git
- release repository: https://github.com/strands-project-releases/openni_wrapper.git
- No changes

openni_wrapper: 0.0.11-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_morse` to `0.2.0-0`:
- upstream repository: https://github.com/strands-project/strands_morse.git
- release repository: https://github.com/strands-project-releases/strands_morse.git
```
* some changes required for kinetic
* Merge pull request #170 <https://github.com/strands-project/strands_morse/issues/170> from heuristicus/example
Add routine configuration to the example
* add routine example
* add stuff to allow routine to run
* Merge pull request #169 <https://github.com/strands-project/strands_morse/issues/169> from heuristicus/example
Basic example which follows documentation
* different topological maps for gmapping and png …
```

strands_morse: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thin_navigation` to `0.0.3-0`:
- upstream repository: https://bitbucket.org/mhanheide/thin_navigation.git
- release repository: https://github.com/LCAS/thin_navigation_release.git
```
* added install targets
```

thin_navigation: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `1.0.4-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Modifications to topological map tools to accommodate topological map editor (#345 <https://github.com/strands-project/strands_navigation/issues/345>)
* fix weird space-colon
* Easier translational movement of waypoints, generic node field updater
Moving the waypoints that are displayed in the topological map in rviz is now
easier - just uses …
```

strands_navigation: 1.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spqrel_navigation` to `0.0.1-0`:
- upstream repository: https://github.com/LCAS/spqrel_navigation.git
- release repository: https://github.com/lcas-releases/spqrel_navigation.git
```
* added dynreconf
* added move_base_msgs
* added tf dep
* added roscpp
* Merge branch 'master' of github.com:LCAS/spqrel_navigation
* ROS planner draft
* Handling temporal obstacles
* Adding management of blind zones in laser scan
* README updated
* Merge branch 'unified_cmake'
* revision and test OK
* added missing build_depend in messgae_generation
* curated package.xml
* all in one CMakeLists.txt for ROS and qibuild
* Adding visualization of variables in …
```

spqrel_navigation: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `people_detection` to `1.0.12-0`:
- upstream repository: https://github.com/lcas/people_detection.git
- release repository: https://github.com/lcas-releases/people_detection.git
```
* changelogs
* Added id to shown image (#43 <https://github.com/lcas/people_detection/issues/43>)
* added id to shown image
* added capability to switch on/off face id display
* Update hardcoded location of opencv
Version changed to 3.2.0, unfortunately we need to hardcode the
location for now.
* [face_detector][test common] Use newly introduced publishtest.
Since the publish rate of the detected face varies every second because one of the …
```

people_detection: 1.0.12-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_perception_people` to `1.6.0-0`:
```
* changed from cdondrup to marc
```
```
* changed from cdondrup to marc
```
```
* changed from cdondrup to marc
```
```
* changed from cdondrup to marc
```
- No changes
```
* changed from cdondrup to marc
```
```
* changed from cdondrup to marc …
```

strands_perception_people: 1.6.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_qsr_lib` to `0.4.0-0`:
- upstream repository: https://github.com/strands-project/strands_qsr_lib.git
- release repository: https://github.com/strands-project-releases/strands_qsr_lib.git
```
* changed maintainer to marc
* update the graphlets class - uses object type if provided in dynamic … (#233 <https://github.com/strands-project/strands_qsr_lib/issues/233>)
* update the graphlets class - uses object type if provided in dynamic args
* updated qstag for tcpp (creates a plane-object node, and rcc4, rcc5 (simple)
* updated qstag for tcpp (creates a plane-object node, and rcc4, rcc5 (simple)
* updated the median filter and returns …
```

strands_qsr_lib: 0.4.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_executive` to `1.2.0-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_executive: 1.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mongodb_store` to `0.3.4-0`:
- No changes
- No changes
- No changes
- No changes

mongodb_store: 0.3.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_morse` to `0.2.2-0`:
- upstream repository: https://github.com/strands-project/strands_morse.git
- release repository: https://github.com/strands-project-releases/strands_morse.git
- No changes

strands_morse: 0.2.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mongodb_store` to `0.3.5-0`:
- previous version for package: `0.3.4-0`
- No changes
- No changes
```
* Merge pull request #203 <https://github.com/strands-project/mongodb_store/issues/203> from strands-project/marc-hanheide-patch-3
added topic_tools`as `CATKIN_DEPEND
* topic_tools as run_depend
* added topic_tools`as `CATKIN_DEPEND
```
- No changes

mongodb_store: 0.3.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_hri` to `0.2.0-0`:
- upstream repository: https://github.com/strands-project/strands_hri.git
- release repository: https://github.com/strands-project-releases/strands_hri.git
```
* changelogs
* Adding an action dispatcher to allow for arbitrary edge actions (#148 <https://github.com/strands-project/strands_hri/issues/148>)
* Adding an action dispatcher to allow for arbitrary edge actions.
* Clean-up
* Contributors: Christian Dondrup, Marc Hanheide
* Adding an action dispatcher to allow for arbitrary edge actions (#148 <https://github.com/strands-project/strands_hri/issues/148>)
* Adding an action dispatcher to allow for arbitrary …
```

strands_hri: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `mongodb_store` to `0.3.6-0`:
- No changes
- No changes
- No changes
- No changes

mongodb_store: 0.3.6-0 in 'indigo/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `strands_executive` to `1.0.9-0`:
```
* indigo-1.0.8
* Updated changelogs
```
```
* Removed stray prism-robots dependency.
* indigo-1.0.8
* Updated changelogs
```
```
* indigo-1.0.8
* Updated changelogs
```
```
* indigo-1.0.8
* Updated changelogs
```
```
* indigo-1.0.8
* Updated changelogs
```
```
* indigo-1.0.8
* Updated changelogs
* …
```

strands_executive: 1.0.9-0 in 'indigo/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_executive` to `1.2.1-0`:
- previous version for package: `1.2.0-0`
- No changes
- No changes
```
* remove bad dependency
* Contributors: Bruno Lacerda
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_executive: 1.2.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `oru_navigation` to `0.2.0-0`:
- No changes
- No changes
- No changes
- No changes
```
* Added new environment model.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Added LICENSE and cleanup.
```
```
* Removed start time checks.
```
- No changes
- No changes
- No changes
- No …

oru_navigation: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.0.3-0`:
```
```

iliad_distribution: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.0.1-0`:
- upstream repository: https://gitsvn-nt.oru.se/iliad/software/iliad_smp.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/iliad_smp_releases.git
```
* adding the cfg directory
* removing the slasj
* removing planners which are not compatible with ompl 1.2.1, having a different branch for fixing bugs issues
* using rrt connect
* fixing the version number
* fixing bug, rotating footprint in the proper way
* fixing bug related to reading the status of the solution
* merging and fixing conflicts with v0.1 branch
* addin AUTHORS and CONTRIBUTORS files
* updating licenses
* returning path only if it …
```

iliad_smp: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne` to `1.2.1-0`:
- upstream repository: https://github.com/OrebroUniversity/velodyne.git
- release repository: https://github.com/LCAS/velodyne-release.git
- No changes
```
* Correct VLP-16 packet rate error.
* Use port number when reading PCAP data.
* Fix g++ 5.3.1 compiler errors.
* Add dynamic_reconfigure and time_offset correction.
* Make input destructors virtual.
* Add VLP-16 support.
* Add support for multiple devices.
* Contributors: Brice Rebsamen, ddillenberger, Patrick Hussey, Andreas
Wachaja, priyankadey, Jack O'Quin
```
- No changes
```
* Fix compile warning for "Wrong initialization order".
* Fix unit tests for …
```

velodyne: 1.2.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.0.4-0`:
- No changes
```
* added restricted distribution
```

iliad_distribution: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru` to `0.1.1-0`:
- upstream repository: https://github.com/marc-hanheide/coordination_oru_ros.git
```
* Merge pull request #4 <https://github.com/FedericoPecora/coordination_oru_ros/issues/4> from marc-hanheide/master
added some more symlink magic
* added some more symlink magic
* Corrected CMakeLists in symlink creation check
* Added conditional to check if symlink creation is necessary
* Added symlink creation in CMakeLists to deal with misplacement of message jar in catkin_make_isolated
* Added launch file for running coordiantion with …
```

coordination_oru: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `kmo_interfaces` to `0.0.4-0`:
- upstream repository: https://gitsvn-nt.oru.se/marc-hanheide/kmo_interfaces.git
- release repository: https://github.com/iliad-project/kmo_interfaces-release.git
- bloom version: `0.6.1`
- No changes
- No changes
```
* Added tf_prefix workaround.
* tf_prefix fix.
* Merged conflicts.
* Added onboard launch files.
* Launchfile for onbard computer.
```
- No changes

kmo_interfaces: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.9-0`:
- upstream repository: https://github.com/LCAS/spencer_people_tracking.git
- previous version for package: `1.0.8-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

spencer_people_tracking: 1.0.9-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.1-1`:
- previous version for package: `1.0.1-0`
```
* Added ROS multimaster to human perception
* Relaying of detector/tracker output topics
* README instructions updated
* First version of people detection and tracking in 2D laser, still requires fix to srl_laser_segmentation and srl_laser_detectors ROS interface
* Fix previous commit, somehow rospy.Rate() causes latency
* Limit publish rate of groundtruth tracked persons to 30 Hz (was 1000 Hz)
* Bugfixes
* …
```

iliad_human_perception: 1.0.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spqrel_navigation` to `0.1.0-0`:
- upstream repository: https://github.com/LCAS/spqrel_navigation.git
- release repository: https://github.com/lcas-releases/spqrel_navigation.git
```
* removed debug prints; fixed parameter names
* naoqi planner refactored first working tests
* changed function name run()
* Partial commit on new refactored naoqi_planner
* Adding min angular vel as ros param
* Added min rotation velocity in rotation-only behaviour
* Fully replaced new version of ros planner after refactoring
* adding recovery procedure to approach goal if there are obstacles in the way
* fixed goal moving while updating the map
* New …
```

spqrel_navigation: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rasberry` to `0.0.1-0`:
```
* added meta package
```
```
* Modified the Picker class to publish /<picker_name>/pose (geometry_msgs.msg.Pose) topic when it reaches a node.
Ros topics were not published while runnning quick sim (simpy.Environment), probably too fast. This needs double checking.
* Changes:
1. env.step() is called in a while loop checking rospy.is_shutdown(), rather than env.run().
2. A bug in the Picker is fixed. The picker no longer re-pick the same row, after it is …
```

rasberry: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.0.1-0`:
```
* added email to package.xml
* added robot in thorvald_model
* added parts to xacro and made more robots
* back from greenhouseot
* initial commit
```
```
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into kinetic-devel
* added a few install targets already
this partially addresses #23 <https://github.com/LCAS/Thorvald/issues/23> but not entirely yet.
* creted gazebo model plugin
* creted gazebo model plugin
* modified include path in …
```

thorvald: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.0.3-0`:
- No changes
- No changes
- No changes
```
* added dep
* added dep
* removed commented out dep
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into kinetic-devel
* added missing dep
```
- No changes
- No changes
- No changes
- No changes
```
* added dep
* added dep
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into kinetic-devel
* added missing dep
```
- No changes

thorvald: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.0.4-0`:
- No changes
```
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into kinetic-devel
* added dep
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into kinetic-devel
* added dep
* Merge branch 'kinetic-devel' of https://github.com/LCAS/Thorvald into kinetic-devel
* added dep
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No …

thorvald: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sicks300` to `1.2.0-0`:
- upstream repository: https://github.com/strands-project/sicks300.git
- release repository: https://github.com/strands-project-releases/sicks300.git
- bloom version: `0.6.3`
- previous version for package: `1.0.6-0`
- No changes

sicks300: 1.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.0.5-0`:
- No changes
```
* added dep
* Added missing dependency
* Contributors: gpdas, larsgrim
* added dep
* Added missing dependency
* Contributors: gpdas, larsgrim
```
- No changes
- No changes
```
* cleaned
* cleaned
```
```
* Added missing dependencies
* Contributors: gpdas
* Added missing dependencies
* Contributors: gpdas
```
```
* this fixes laser visualisation problems in Rviz
* Contributors: Jaime Pulido Fentanes
* this fixes laser …
```

thorvald: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

indigo/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `0.1.19-0`:
- previous version for package: `0.1.16-0`
```
* prepare indigo release
* 0.1.18
* updated changelogs
* 0.1.17
* changelogs
* Contributors: LCAS build farm, Marc Hanheide
* 0.1.18
* updated changelogs
* 0.1.17
* changelogs
* Contributors: LCAS build farm, Marc Hanheide
```
```
* prepare indigo release
* 0.1.18
* updated changelogs
* 0.1.17
* changelogs
* Contributors: LCAS build farm, Marc Hanheide
* 0.1.18
* updated changelogs
* 0.1.17
* changelogs
* Contributors: LCAS build farm, Marc Hanheide
```
```
* …
```

lcas_teaching: 0.1.19-0 in 'indigo/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `1.0.5-0`:
- previous version for package: `1.0.4-0`
```
```
- No changes
```
* updated email
```
- No changes
- No changes
- No changes
- No changes
```
* Merge pull request #351 <https://github.com/strands-project/strands_navigation/issues/351> from heuristicus/indigo-devel
Can now place nodes with RMB to stop automatic edge creation
* Can now place nodes with RMB to stop automatic edge creation …
```

strands_navigation: 1.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.1.0-0`:
```
* Adding bicycle state space to use the steering_functions package
* Providing example on how to launch the service
* Adding move_base global_planner plug-in
* Adding new cost bound param
* Adding new planners RRTX and RRT# and initial implementation of PS-RRT
* Adding ompl_visualization tool to display planner graph in RviZ
* Contributors: Palmieri Luigi (Robert Bosch GmbH, CR/AER)
```

iliad_smp: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `steering_functions` to `1.0.5-0`:
- upstream repository: https://github.com/iliad-project/steering_functions.git
- release repository: https://github.com/lcas-releases/steering_functions.git
- previous version for package: `1.0.4-0`
```
* install everything in headers
```

steering_functions: 1.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_nav_branch` to `2.0.0-0`:
- upstream repository: https://github.com/strands-project/navigation.git
- release repository: https://github.com/strands-project-releases/navigation-additions.git
```
* removed duplicate
* more renames due to new package name
```

lcas_nav_branch: 2.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.1.2-0`:
```
* Merge branch 'v0.1.0-branch'
* updating 3rd party license file
* extending list of params
* entering the service name as param
* example launch file for move_base plug in
* Merge branch 'v0.1.0-branch' of https://gitsvn-nt.oru.se/palmieri/iliad_smp into v0.1.0-branch
* Exporting all the targets properly
* Contributors: Luigi Palmieri (CR/AER)
```

iliad_smp: 0.1.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru_ros` to `0.2.0-0`:
```
* Merge branch 'master' of github.com:FedericoPecora/coordination_oru_ros
* changed install to include dependency packages
* Changed to RVizVisualization in NCFM main node
* Added RVIZVisualization in MainNode
* Updated to new version of coordination_oru (0.1.4)
* Now depends on snapshots of coordination_oru and metacsp
* Contributors: Federico Pecora, Marc Hanheide …
```

coordination_oru_ros: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru_ros` to `0.2.1-0`:
```
* .gitignore updated to not include cradle build files
* message generation
* added message_generation
```

coordination_oru_ros: 0.2.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `genjava` to `1.0.0-0`:
- upstream repository: https://github.com/LCAS/genjava.git
- release repository: https://github.com/lcas-releases/genjava.git
```
* lcas version
* Merge pull request #15 <https://github.com/lcas/genjava/issues/15> from jubeira/gradle_3-5-1
Gradle update: 3.5.1
* Using 'doLast' instead of '<<' operator in templates.
* Gradle update: 3.5.1
* Merge pull request #13 <https://github.com/lcas/genjava/issues/13> from meyerj/patch-1
Fix non-existent dependency warning for the catkin API (fix #7 <https://github.com/lcas/genjava/issues/7>)
* Fix non-existent dependency warning for the catkin API (fix #7 …
```

genjava: 1.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.0.5-0`:
```
* updated for new packages
* Merge branch 'master' of https://gitsvn-nt.oru.se/iliad/software/iliad_metapackage
* added kmo and velodyne
```
```
* updated for new packages
```

iliad_distribution: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru_ros` to `0.3.0-0`:
```
* removed invalid dep
* make messages an own package
* added msgs package
* removed invalid dep
* make messages an own package
* added msgs package
```
```
* faithful attempt...
* make messages an own package
```

coordination_oru_ros: 0.3.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru_ros` to `0.3.1-0`:
- previous version for package: `0.3.0-0`
- No changes
```
* added missing dep
```

coordination_oru_ros: 0.3.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.1.3-0`:
- previous version for package: `0.1.2-0`
```
* Merge branch 'master' of https://gitsvn-nt.oru.se/palmieri/iliad_smp
* setting PRM* as standard planner
```

iliad_smp: 0.1.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru_ros` to `0.4.0-1`:
- previous version for package: `0.3.1-0`
```
* Merge pull request #5 <https://github.com/FedericoPecora/coordination_oru_ros/issues/5> from FedericoPecora/message_generation
Refactoring into separate packages for message dependencies
* Contributors: Federico Pecora
```
```
* Corrected iliad_smp_global_planner reference in launch files
* Merge pull request #5 <https://github.com/FedericoPecora/coordination_oru_ros/issues/5> from FedericoPecora/message_generation
Refactoring into …
```

coordination_oru_ros: 0.4.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.0.7-0`:
- previous version for package: `0.0.6-0`
```
* changelogs
* basic structure for packages with launch directories
* basic structure for packages with launch directories
```
```
* bugfix about missing catkin dep
* added placeholders
* basic structure for packages with launch directories
* bugfix about missing catkin dep
* added placeholders
* basic structure for packages with launch directories
* …
```

iliad_distribution: 0.0.7-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.1.4-0`:
- previous version for package: `0.1.3-0`
```
* Considering also dynamic obstacles into the costmap2D
* adding example file to launch the iliad smp planner on the citi truck
```

iliad_smp: 0.1.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rasberry` to `0.0.2-0`:
```
* more deps
* Merge branch 'master' of https://github.com/LCAS/RASberry into topo_nav
* Contributors: Marc Hanheide, gpdas
```
```
* Merge pull request #50 <https://github.com/LCAS/RASberry/issues/50> from gpdas/master (Secondary head lane & Config file format changes)
Tested OK.
No major change in any agent behaviours.
* README updates
* Config file modifications
Recent commits increased the number of config parameters and the parameters are no longer loaded to param server. The …
```

rasberry: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.33-0`:
```
* Working version
* Contributors: Daniel Adolfsson
```

perception_oru: 1.0.33-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.1-2`:
- previous version for package: `1.0.1-1`
```
* Added ROS multimaster to human perception
* Relaying of detector/tracker output topics
* README instructions updated
* First version of people detection and tracking in 2D laser, still requires fix to srl_laser_segmentation and srl_laser_detectors ROS interface
* Fix previous commit, somehow rospy.Rate() causes latency
* Limit publish rate of groundtruth tracked persons to 30 Hz (was 1000 Hz)
* Bugfixes
* …
```

iliad_human_perception: 1.0.1-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.0.6-0`:
```
* Merge pull request #36 <https://github.com/LCAS/Thorvald/issues/36> from gcielniak/kinetic-devel
Metapackage added so that all packages can be installed in one go
* Additional metapackage for thorvald simulator.
Other minor fixes:
- thorvald_base depends now on thorvald_model
- fixed model path in thorvald_base launch file
* Metapackage added so that all thorvald packages can be installed in one go: sudo apt-get install ros-kinetic-thorvald.
* Contributors: Grzegorz Cielniak, …
```

thorvald: 0.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.34-0`:
- previous version for package: `1.0.33-0`
```
* Polished tutorial
* Contributors: Daniel Adolfsson
```
```
* polished tutorial
* Contributors: Daniel Adolfsson
```
- No changes
```
* finished with new reader
* Contributors: Daniel Adolfsson
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

perception_oru: 1.0.34-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.36-0`:
- previous version for package: `1.0.34-0`
```
* fixed dependencies in graph_localization
* fixed dependencies in graph_map
```
```
* fixed dependencies in graph_map
* fixed dependencies in graph_localization
```
```
* fixed dependencies in ndt_fuser
```
```
* fixed dependencies in ndt_generic
* fixed dependencies in ndt_generic
```
- No changes
- No changes
- No …

perception_oru: 1.0.36-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.37-0`:
- previous version for package: `1.0.36-0`
- No changes
- No changes
```
* ndt_fuser fix
* ndt_fuser fix
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* ndt_rviz added dependency to eigen conversions
```
- No changes
```
* ndt_fuser fix
```

perception_oru: 1.0.37-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.38-0`:
- previous version for package: `1.0.37-0`
- No changes
- No changes
```
* fixed dependencies in ndt_fuser
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* fixed dependencies in ndt_rviz
```
- No changes
- No changes

perception_oru: 1.0.38-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.39-0`:
- previous version for package: `1.0.38-0`
- No changes
- No changes
```
* fix for ndt fuser
```
- No changes
```
* fix for ndt fuser
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

perception_oru: 1.0.39-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.40-0`:
- previous version for package: `1.0.39-0`
- No changes
- No changes
```
* updated ndt_fuser fix
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

perception_oru: 1.0.40-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_oru` to `1.0.41-0`:
- previous version for package: `1.0.40-0`
- No changes
```
* Fixed >> vs > > problem.
* Contributors: Chittaranjan Srinivas Swaminathan, Chittaranjan Swamminathan, Henrik Andreasson, Malcolm Mielle, Tomasz Kucner, daniel, daniel adolfsson, mailto:dla.adolfsson@gmail.com
```
```
* merged with removal of MCL-NDT
* ported 3d localization
* Prior for 2D localisation with NDTH
* Contributors: Chittaranjan Swamminathan, Henrik Andreasson, Malcolm Mielle, Tomasz Kucner, daniel, daniel …
```

perception_oru: 1.0.41-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rasberry` to `0.0.3-0`:
- No changes
```
* Fixed rasberry_actors/maps reference
* Seperated the gazebo world with polytunnels and actor spawning into seperate packages (rasberry_gazebo and actor_gazebo, respectively).
There is also a rasberry_bringup package that launches everything together
* Contributors: adambinch
* Fixed rasberry_actors/maps reference
* Seperated the gazebo world with polytunnels and actor spawning into seperate packages (rasberry_gazebo and actor_gazebo, respectively).
There is also a …
```

rasberry: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.1.0-0`:
- previous version for package: `0.0.6-0`
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* …
```

thorvald: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_simulator8` to `1.1.0-0`:

velodyne_simulator8: 1.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_simulator8` to `1.1.1-1`:
- previous version for package: `1.1.0-0`
```
* Merge branch 'gazebo8' of https://github.com/LCAS/velodyne_simulator into gazebo8
* Contributors: mailto:mfernandezcarmona@lincoln.ac.uk
```
```
* removed gazebo8_ros from CMakelists
* Merge branch 'gazebo8' of https://github.com/LCAS/velodyne_simulator into gazebo8
* corrected dependency to point to gazebo8
* Contributors: mailto:mfernandezcarmona@lincoln.ac.uk
```
```
* Merge branch 'gazebo8' of https://github.com/LCAS/velodyne_simulator into …
```

velodyne_simulator8: 1.1.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `1.0.6-0`:
- previous version for package: `1.0.5-0`
- No changes
- No changes
```
* new c++11 (#359 <https://github.com/strands-project/strands_navigation/issues/359>)
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge pull request #358 <https://github.com/strands-project/strands_navigation/issues/358> from Jailander/rasberry-devel
re-adding ability to work with other planners
* Fixes bug on service call for adding …
```

strands_navigation: 1.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.1.0-1`:
- previous version for package: `0.1.0-0`
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* changelogs
```
```
* 0.0.7
* …
```

thorvald: 0.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.1-0`:
```
* adopted for release
* Extending README with docker use case
* Add note about rosout
* Add support for remapping, a way for dealing with multiple robots
* Add support for services
* Cleanup docs and add test for params
* Added efficient management of rosbridge subscribers
* Update client, latest version supports general introspection calls and param handling
* optimize publication
* Fixes to make it work, damn closures
* Initial commit
* Contributors: Marc Hanheide, Sammy Pfeiffer
```

rosduct: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.1.1-0`:
- previous version for package: `0.1.0-1`
- No changes
```
* Merge branch 'kinetic-devel' of github.com:LCAS/Thorvald into kinetic-devel
* Dependency fixes:
Some dependency fixes thorvald_2dnav, thorvald_base and thorvlad_model
* Contributors: gpdas
```
```
* Merge branch 'kinetic-devel' of github.com:LCAS/Thorvald into kinetic-devel
* Dependency fixes:
Some dependency fixes thorvald_2dnav, thorvald_base and thorvlad_model
* Contributors: gpdas
```
- No changes
- No changes
- No changes
- No changes
```
* Merge branch …
```

thorvald: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.2.0-0`:
- No changes
- No changes
- No changes
```
* fixed gazebo8?
* fixed package.xml
```
- No changes
```
* removed gazebo_plugins
* fixed gazebo8?
* fixed package.xml
```
- No changes
```
* fixed gazebo8?
* fixed package.xml
```
- No changes
- No changes
- No changes
- No changes

thorvald: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rasberry` to `0.0.4-0`:
- No changes
```
* removed depend to gazebo_ros
* Added simulation with velodyne and kinect2, rviz config file to visualize them and changed actor to use gpu based simulated laser
* Contributors: Marc Hanheide, mailto:mfernandezcarmona@lincoln.ac.uk
```
```
* Added simulation with velodyne and kinect2, rviz config file to visualize them and changed actor to use gpu based simulated laser
* Changing topological map name
* adding simulation start-up script
* Contributors: Jaime Pulido …
```

rasberry: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `depth_sensors` to `0.0.1-0`:
```
* Maintainer updated
* simple camera model for pose-to-pixel-space projection debugging
* moved Kinect V2 control into its own package
* moved Kinect V2 description into its own package
* moved Senz3d description into its own package
* metapackage for depth sensors
* Contributors: lude-ma, mailto:mfernandezcarmona@lincoln.ac.uk
```
```
* former kinect2_description now as part of a bigger one
* Contributors: mailto:mfernandezcarmona@lincoln.ac.uk
```
```
* Maintainer …
```

depth_sensors: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.2-0`:

iai_kinect2: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.4-0`:

iai_kinect2: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.5-0`:

iai_kinect2: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.6-0`:

iai_kinect2: 0.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.7-0`:
- previous version for package: `0.0.6-0`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

iai_kinect2: 0.0.7-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `libfreenect2` to `0.0.8-0`:
- upstream repository: https://github.com/LCAS/libfreenect2.git
- release repository: https://github.com/lcas-releases/libfreenect2.git

libfreenect2: 0.0.8-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.8-0`:
- previous version for package: `0.0.7-0`
- No changes
```
* Libfreenect2 dev (#2 <https://github.com/LCAS/iai_kinect2/issues/2>)
* Changed freenect2 from submodule to subproject with git. catkin_make_isolated --install works
* m.ch.
* added git as a dependence and install targets
* w.i.p.
* freenect2 moved to its own fork
* Works in my docker...
```
- No changes
- No changes
- No changes

iai_kinect2: 0.0.8-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.9-0`:
- previous version for package: `0.0.8-0`
- No changes
```
* Changed readme.md file in kinect2_bridge
```
- No changes
- No changes
- No changes

iai_kinect2: 0.0.9-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.2.1-0`:
- No changes
- No changes
```
* added leading slash to joint names
```
```
* added leading slash to joint names
```
- No changes
- No changes
- No changes
```
* Fixes in thorval_model for multi-thorvald simulation
Changes in thrvald_model.xacro and sensor_modules_lincoln.xacro
- corrected the indentation
- arg tf_prefix doesn't need a trailing "/"
- added missing tf_prefix for links
- added missing namespace for topics
* Merge pull …
```

thorvald: 0.2.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_ui` to `0.1.1-0`:
- upstream repository: https://github.com/strands-project/strands_ui.git
- release repository: https://github.com/strands-project-releases/strands_ui.git
- previous version for package: `0.1.0-0`
```
* Merge pull request #107 <https://github.com/strands-project/strands_ui/issues/107> from strands-project/sync_reply
resolved sync issue with clearing queue
* resolved sync issue with clearing queue
* Contributors: Lindsey User, Marc Hanheide
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
```

strands_ui: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.2-0`:
```
* latch remote topics
* latch remote topics
```

rosduct: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.3-0`:
```
* latching was a stupid idea
```

rosduct: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `depth_sensors` to `0.0.2-0`:
```
* Included asus
* Included asus
```
```
```
- No changes
- No changes
- No changes
- No changes
- No changes

depth_sensors: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `depth_sensors` to `0.0.3-0`:
```
removed mesh directory from install. Asus mesh is taken from turtlebot_description package
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

depth_sensors: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ndt_core` to `2.0.0-0`:
- upstream repository: https://gitsvn-nt.oru.se/software/ndt_core.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/releases/ndt_core-release.git
```
* fixed tags in package.xml
* copying core packages from perception_oru to ndt_core
```
```
* packages
* add compilation only on dev success
* add compilation only on dev success
* pushing pose queue
* removed bug which allocated twice as much memory
* changed sensor offset
* Updated HX motion model. Commented out the old model acessing method.
* Fixed motion_model variable assignment bug.
* working on polar ndt
* copying …
```

ndt_core: 2.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ndt_tools` to `2.0.0-0`:
- upstream repository: https://gitsvn-nt.oru.se/software/ndt_tools.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/releases/ndt_tools-release.git
```
* Intiial commit
```
```
* Intiial commit
```
```
* Intiial commit
```
```
* Merge branch 'master' of gitsvn-nt.oru.se:software/ndt_tools
* removed ndt_calibration
* Intiial commit
* Contributors: Tomasz Kucner, daniel
```
```
* Merge branch 'master' of gitsvn-nt.oru.se:software/ndt_tools
* backup
* Intiial commit
* Contributors: Tomasz …
```

ndt_tools: 2.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `graph_map` to `2.0.0-0`:
- upstream repository: https://gitsvn-nt.oru.se/iliad/software/graph_map.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/releases/graph_map-release.git
```
* updated changelogs
* Contributors: Daniel Adolfsson, Henrik Andreasson, daniel, daniel adolfsson, mailto:dla.adolfsson@gmail.com, sunliamm
```
```
* updated changelogs
* Contributors: Daniel Adolfsson, Henrik Andreasson, daniel, daniel adolfsson, mailto:dla.adolfsson@gmail.com, sunliamm
```
```
* updated changelogs
* Contributors: Daniel Adolfsson, Henrik Andreasson, daniel, daniel adolfsson, mailto:dla.adolfsson@gmail.com, sunliamm
```
```
* …
```

graph_map: 2.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.0.8-0`:
- previous version for package: `0.0.7-0`
```
* removed unnecessary ones and added graph_localisation
```
```
* removed unnecessary ones and added graph_localisation
```
```
* removed unnecessary ones and added graph_localisation
```
```
* removed unnecessary ones and added graph_localisation
```
- No changes

iliad_distribution: 0.0.8-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `cliff_map` to `0.0.1-0`:
- upstream repository: https://github.com/ksatyaki/cliffmap_ros.git
```
* Add LGPLv3
* ROS service is ready.
* Add grid map organize function + variables
* Functions to interpret the map as a gridmap.
* Contributors: Chittaranjan Srinivas Swaminathan
```

cliff_map: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.4-0`:
```
* Merge pull request #2 <https://github.com/LCAS/rosduct/issues/2> from MFernandezCarmona/master
Update package.xml
* reintroduced pydispatcher
* remove pydispatch
the problem is we need pip install pydispatcher, not pydispatch . So for now we remove this dependency until we have a deb package for this python package
* Caching Service exceptions...
* Update conversions.py
These should solve the following errors I had runing rosduct:
ImportError: No module named …
```

rosduct: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `coordination_oru_ros` to `0.5.0-0`:
- previous version for package: `0.4.0-1`
- No changes
```
* post demo
* Arena demo done
* New cycle 3 and reverse service implemented in tracker
* Added remote launch files and modified truncating service
* Added arena launch files; now depends on coordination_oru v. 0.3.2
* Bumped up version of coordination_oru to 0.3.1
* Point and click remote launch.
* Fixed remapping of topics...
* Added service to abort mission
* Adding ability to interrupt mission (incomplete); now …
```

coordination_oru_ros: 0.5.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.1.0-0`:
- previous version for package: `1.0.8-0`
```
* support for Polar Models (#22 <https://github.com/LCAS/bayestracking/issues/22>)
* Added 2D Polar Observation Model
* no default parameter values in redeclared functions
* proper building
* Changes for backward-compatibility
* Backward-compatibility of example code
* Fixed condition logic that caused label checks to always be used (#21 <https://github.com/LCAS/bayestracking/issues/21>)
* Update snapcraft.yaml
* Update snapcraft.yaml
* Update snapcraft.yaml
* …
```

bayes_tracking: 1.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_perception_people` to `1.7.0-0`:
- previous version for package: `1.6.0-0`
```
* Adapting to changes in bayestracking (#220 <https://github.com/strands-project/strands_perception_people/issues/220>)
* Adapted to scosar/bayestracking with 2D Polar Model and Added option to select Particle Filter
* random fixes
* Adapted to backward-compatibility changes of bayestracking
* Namespaces and topics specified as parameters. (#218 <https://github.com/strands-project/strands_perception_people/issues …
```

strands_perception_people: 1.7.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `executive_smach_strands` to `3.0.0-0`:
- upstream repository: https://github.com/strands-project/executive_smach.git
- release repository: https://github.com/strands-project-releases/executive_smach.git
```
* changed maintainer for local version
* Merge pull request #5 <https://github.com/strands-project/executive_smach/issues/5> from ros/indigo-devel
Import upstream
* 2.0.1
* changelog 2.0.1
* Merge pull request #48 <https://github.com/strands-project/executive_smach/issues/48> from 130s/i/update_ci4
[indigo-devel] Sync to master branch. Update CI conf to enable ROS IJKL
* [package.xml] Update maintainer.
* packaging: switching to format …
```

executive_smach_strands: 3.0.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_social` to `0.0.16-0`:
- upstream repository: https://github.com/strands-project/strands_social.git
- release repository: https://github.com/strands-project-releases/strands_social.git
- No changes
- No changes
- No changes
```
* added missing install targets
* Contributors: Jailander
```
```
* Merge pull request #47 <https://github.com/strands-project/strands_social/issues/47> from gestom/hydro-devel
Social card reader parameters reconfigurable.
* Social card reader parameters reconfigurable.
* Contributors: Marc Hanheide, Tom Krajnik
```
- No changes
- No changes

strands_social: 0.0.16-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_social` to `0.1.0-0`:
- upstream repository: https://github.com/strands-project/strands_social.git
- release repository: https://github.com/strands-project-releases/strands_social.git
- previous version for package: `0.0.16-0`
- No changes
- No changes
- No changes
- No changes
```
* Merge pull request #51 <https://github.com/strands-project/strands_social/issues/51> from Jailander/hydro-devel
Removing datamatrix read package
* removing deprecated dependency
* Contributors: Jaime Pulido Fentanes, Marc Hanheide
```
- No changes

strands_social: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_detector` to `0.0.1-0`:
- upstream repository: https://github.com/LCAS/pcl_detector.git
- release repository: https://github.com/lcas-releases/pcl_detector.git
```
* extracted from original repo
* Initial commit
```

pcl_detector: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.2.2-0`:
- previous version for package: `0.2.1-0`
```
* cleanup in package.xml
```
```
* added argument in localization_local.launch to kill publication of tf transform
* holonomic robot
* cleanup in package.xml
* added license
* removed dep on razor imu
* Cleaned up thorvald_2dnav and created more sensible launch files
* Changed from using positions to velocities for odom and added slash to tf prefix
* removed 'greenhouse' costmap layer
* Contributors: adambinch, larsgrim
```
```
* odom tf params and defaults …
```

thorvald: 0.2.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.1.5-1`:
- previous version for package: `0.1.4-0`
```
* Integrating CLiFF sampling, can be used by several OMPL based planners
* Capable of reading update grid maps provided by the coordination_oru package, a measure to reduce deadlocks
```

iliad_smp: 0.1.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sicks300` to `1.2.1-0`:
- upstream repository: https://github.com/strands-project/sicks300.git
- release repository: https://github.com/strands-project-releases/sicks300.git
- previous version for package: `1.2.0-0`
- No changes

sicks300: 1.2.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mongodb_store` to `0.4.2-1`:
- previous version for package: `0.3.5-0`
```
* instead of lsb-release read /etc/os-version from CMake to find OS version
* Contributors: Ferenc Balint-Benczedi
```
```
* instead of lsb-release read /etc/os-version from CMake to find OS version
* Contributors: Ferenc Balint-Benczedi
```
```
* instead of lsb-release read /etc/os-version from CMake to find OS version
* Contributors: Ferenc Balint-Benczedi
```
- No changes

mongodb_store: 0.4.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.0.2-0`:
```
* cleaned
* launch file and configurable port
```

slackeros: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.0.3-0`:
```
* fixes #3 <https://github.com/marc-hanheide/slackeros/issues/3>
* fix #1 <https://github.com/marc-hanheide/slackeros/issues/1> and #2 <https://github.com/marc-hanheide/slackeros/issues/2>
* robust eception handling
* fixed launch install
```

slackeros: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.0.4-0`:
```
* roslogger works. fixes #4 <https://github.com/marc-hanheide/slackeros/issues/4>
```

slackeros: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `cliff_map` to `0.0.2-0`:
- upstream repository: https://github.com/ksatyaki/cliffmap_ros.git
```
* Add missing target
* Add header to msg
```

cliff_map: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lidar_object_detection` to `0.0.2-0`:
- upstream repository: https://github.com/LCAS/lidar_object_detection_release.git
- release repository: https://github.com/lcas-releases/lidar_object_detection_release.git
```
* add tf_conversions
* added nav_msgs dep
* more fixed
* attempt to better install and fix build problems
* changed to use cv_bridge
* fix two bugs in the cloud normailization
* update intensity model
* remove third parties
* ready to release
* Initial commit
* Contributors: Kevin Li Sun, Marc Hanheide, kevin
```

lidar_object_detection: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `depth_sensors` to `0.0.4-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

depth_sensors: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_simulator8` to `1.1.3-1`:
- previous version for package: `1.1.1-1`
- No changes
- No changes
- No changes

velodyne_simulator8: 1.1.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.10-0`:
- upstream repository: https://github.com/LCAS/spencer_people_tracking.git
- previous version for package: `1.0.9-0`
```
* Merge pull request #47 <https://github.com/LCAS/spencer_people_tracking/issues/47> from LCAS/master
1.0.8
```
```
* Merge pull request #47 <https://github.com/LCAS/spencer_people_tracking/issues/47> from LCAS/master
1.0.8
```
```
* Merge pull request #47 <https://github.com/LCAS/spencer_people_tracking/issues/47> from LCAS/master
1.0.8
```
```
* Merge …
```

spencer_people_tracking: 1.0.10-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `persistent_topics` to `1.5.2-0`:
- upstream repository: https://github.com/marc-hanheide/persistent_topics.git
- release repository: https://github.com/lcas-releases/persistent_topics.git
- No changes

persistent_topics: 1.5.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `libfreenect2` to `0.0.9-0`:
- upstream repository: https://github.com/LCAS/libfreenect2.git
- release repository: https://github.com/lcas-releases/libfreenect2.git
- previous version for package: `0.0.8-0`
```
* Merge pull request #1 <https://github.com/LCAS/libfreenect2/issues/1> from LCAS/cuda9.0
changed dependency to cuda 9.0
* changed dependency to cuda 9.0
* Contributors: Marc Hanheide, mailto:mfernandezcarmona@lincoln.ac.uk
```

libfreenect2: 0.0.9-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rgbd_gpu_detector` to `2.0.1-0`:
```
* Remove Python setup
* Configure CUDA 9.0 and CUDNN dependencies for buildfarm
* Adding dependency to cuda_latest
* Initial commit
* Updated CMakeLists for build farm
* Removing unused files
* Move weights file into .ros for buildfarm deployment
* Update README
```

rgbd_gpu_detector: 2.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rgbd_gpu_detector` to `2.0.2-0`:
- previous version for package: `2.0.1-0`
```
* Add missing install targets for launch files and cfg
```

rgbd_gpu_detector: 2.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.0.1-0`:
```
* fixed cmake
* added stub package
```

uol_cmp9767m: 0.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.2-0`:
- previous version for package: `1.0.1-2`
```
* Saving Rviz config
* Saving current version for ILIAD
* Solved bug
* Fix to odom_to_tf script
* Adding odom_to_tf script. Bugfixes to playback launch file.
* Saving progress on refactoring of tracking pipeline, namespace changes, improved bagfile postprocessing
* Saving progress on launch files
* Launch file structure set up, now need to be filled with contents
* Restructuring launch files. Moved central …
```

iliad_human_perception: 1.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.3-0`:
- previous version for package: `1.0.2-0`
```
* Add missing launch files to install space
```

iliad_human_perception: 1.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_simulator8` to `1.1.4-1`:
- previous version for package: `1.1.3-1`
```
* corrected offset
* Contributors: ILIAD user
```
- No changes
- No changes

velodyne_simulator8: 1.1.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.4-0`:
- previous version for package: `1.0.3-0`
```
* First version of tracking (Kinect v2 only)
* Updated postprocessing script
```

iliad_human_perception: 1.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.0.2-0`:
```
* Merge pull request #1 <https://github.com/LCAS/CMP9767M/issues/1> from gpdas/master
Modified thorvald-sim.launch to launch robot in an empty world
* Modified thorvald-sim.launch to launch robot in an empty world
* Contributors: Marc Hanheide, gpdas
```

uol_cmp9767m: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.5-0`:
- previous version for package: `1.0.4-0`
```
* Use odom frame for tracking
```

iliad_human_perception: 1.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rgbd_gpu_detector` to `2.0.3-0`:
- previous version for package: `2.0.2-0`
```
* Fix error message due to missing nodelet_plugins.xml
```

rgbd_gpu_detector: 2.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.6-0`:
- previous version for package: `1.0.5-0`
```
* Use high-precision model
* Integrate new version of Kevin's Velodyne detector
```

iliad_human_perception: 1.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.1.6-0`:
- previous version for package: `0.1.5-1`
```
* Bug fix, setting type for the BicycleStateSpace
```

iliad_smp: 0.1.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.2.0-0`:
- previous version for package: `1.1.0-0`
```
* Flexible id associations (#23 <https://github.com/LCAS/bayestracking/issues/23>)
* fix to use local headers first
* proper support for tagged tracking
* added tags tracking example
* fix bug to only assign if not named yet
```

bayes_tracking: 1.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.3.0-0`:
- previous version for package: `1.2.0-0`
```
* fixed tag check for LABELED (#24 <https://github.com/LCAS/bayestracking/issues/24>)
```

bayes_tracking: 1.3.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.4.0-0`:
- previous version for package: `1.3.0-0`
```
* added pruneNamedTracks (#25 <https://github.com/LCAS/bayestracking/issues/25>)
* fixed tag check for LABELED
* added pruneNamedTracks
* removed print
* pruning now works
```

bayes_tracking: 1.4.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_perception_people` to `1.8.0-0`:
- previous version for package: `1.7.0-0`
```
* WIP: working towards tag-aware tracking (#221 <https://github.com/strands-project/strands_perception_people/issues/221>)
* WIP
* WIP
* wip
* good testing node
* WIP
* Fixed count
* WIP
* more documentation and testing
* colors for variances
* added rviz config
* prune_named added
* legacy param support
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No …

strands_perception_people: 1.8.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.5-0`:
```
* removed cuplicate dep
* removed cuplicate dep
* removed cuplicate dep
* Merge branch 'cwbollinger-master'
* Merge branch 'master' of https://github.com/cwbollinger/rosduct into cwbollinger-master
* Added services to remove topic/service from bridge
* Added services to dynamically expose topic/service
* Commented out over-verbose logging
* Exit rosduct when connection is broken.
Can't seem to recover afterwards, so might as well exit
* Experiments to enable reconnections
* …
```

rosduct: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.0.3-0`:
```
* Merge pull request #4 <https://github.com/LCAS/CMP9767M/issues/4> from gpdas/master
Adding sensors to the simulated robot
* Initial world file for uol_cmp9767m_base
ground texture model added
new world file to use the new ground model
launch file updated to load the new world
CMakeLists updated with a hook to copy the models directory
* dependency correction
* fixes to hokuyo and velodyne parameters
* Fix in velodyne parameters
* Adding hokuyo and velodyne sensors in …
```

uol_cmp9767m: 0.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.0.4-0`:
```
* Merge pull request #5 <https://github.com/LCAS/CMP9767M/issues/5> from gpdas/master
Updated ground textures
* Cleanup
* Merge branch 'master' of github.com:LCAS/CMP9767M
* New ground textures and enclosure are added
Fixed missing install targets in CMakeLists
World file updated with models with new textures
New wider robot configuration within the package
Hokuyo laser ray visibility in gazebo is disabled
* Contributors: Marc Hanheide, gpdas
```

uol_cmp9767m: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_simulator8` to `1.1.5-1`:
- previous version for package: `1.1.4-1`
```
* Merge pull request #4 <https://github.com/LCAS/velodyne_simulator/issues/4> from gpdas/gazebo8
some file still linked to velodyne_description instead of *8
* Some file links to velodyne_description replaced with corresponding ones in velodyne_description8
* Contributors: Marc Hanheide, gpdas
```
- No changes
- No changes

velodyne_simulator8: 1.1.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.6-0`:
```
* Fix: ROSDuctConnection() object's latch attribute not set (#5 <https://github.com/LCAS/rosduct/issues/5>)
* Fix for missing latch for local and remote topics - in ROSDuctConnection objects
Setting the default value of msg.latch for local and remote topics to False
If the latch value is given in the config (takes up to 4 values for topics), that value is taken
* msg.latch takes string or bool values for local and remote topics
Fix in check_if_msgs_are_installed() when local_topics …
```

rosduct: 0.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_ui` to `0.2.0-0`:
- upstream repository: https://github.com/strands-project/strands_ui.git
- release repository: https://github.com/strands-project-releases/strands_ui.git
```
* Merge pull request #108 <https://github.com/strands-project/strands_ui/issues/108> from francescodelduchetto/pull-req
Catch cancel_goal of the action and stop the player accordingly.
* goal preemption stops marytts speaking
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_ui: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `catkin_simple` to `0.2.0-0`:
- upstream repository: https://github.com/LCAS/catkin_simple.git
- release repository: https://github.com/lcas-releases/catkin_simple.git
```
* Merge pull request #27 <https://github.com/catkin/catkin_simple/issues/27> from flaviofontana/patch-1
add dynamic reconfigure info to the readme
* add dynamic reconfigure info to the readme
* Merge pull request #26 <https://github.com/catkin/catkin_simple/issues/26> from flaviofontana/add_dynamic_reconfigure
added autodetection of dynamic_reconfigure
* fixed indentation
* adding build dependency on gencfg
* adding all cfg all files at once
* added autodetection of …
```

catkin_simple: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_catkin_c11` to `1.8.2-0`:
- No changes

pcl_catkin_c11: 1.8.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_catkin_c11` to `1.8.3-1`:
- previous version for package: `1.8.3-0`
```
* Merge pull request #1 <https://github.com/LCAS/pcl_catkin/issues/1> from LCAS/submodule
attempt to build as subdir
* attempt to build as subdir
* Contributors: Marc Hanheide, root
```

pcl_catkin_c11: 1.8.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_catkin_c11` to `1.8.3-2`:
- previous version for package: `1.8.3-1`
```
* Merge pull request #1 <https://github.com/LCAS/pcl_catkin/issues/1> from LCAS/submodule
attempt to build as subdir
* attempt to build as subdir
* Contributors: Marc Hanheide, root
```

pcl_catkin_c11: 1.8.3-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_catkin_c11` to `1.8.3-3`:
- previous version for package: `1.8.3-2`
```
* Merge pull request #1 <https://github.com/LCAS/pcl_catkin/issues/1> from LCAS/submodule
attempt to build as subdir
* attempt to build as subdir
* Contributors: Marc Hanheide, root
```

pcl_catkin_c11: 1.8.3-3 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_conversions_c11` to `0.2.2-0`:
- upstream repository: https://github.com/LCAS/pcl_conversions.git
- release repository: https://github.com/lcas-releases/pcl_conversions.git
```
* renaming
* renaming
* changed name and maintainer
* Merge pull request #1 <https://github.com/LCAS/pcl_conversions/issues/1> from ethz-asl/feature/switch_to_pcl_catkin
switched from PCL to pcl_catkin dependency
* switched from PCL to pcl_catkin dependency
* Merge pull request #22 <https://github.com/LCAS/pcl_conversions/issues/22> from ros-perception/paulbovbel-patch-1
Remove duplicated line
* Remove duplicated line
* Contributors: Marc Hanheide, Marko Panjek, …
```

pcl_conversions_c11: 0.2.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_conversions_c11` to `0.2.3-0`:
- upstream repository: https://github.com/LCAS/pcl_conversions.git
- release repository: https://github.com/lcas-releases/pcl_conversions.git
```
```

pcl_conversions_c11: 0.2.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `marvelmind_nav_lcas` to `1.0.9-0`:
- upstream repository: https://github.com/LCAS/ros_marvelmind_package.git
- release repository: https://github.com/lcas-releases/ros_marvelmind_package.git
```
* ROS_INFOs along with topic publish are disabled
* added install targets
* Contributors: Marc Hanheide, gpdas, thorvald
```

marvelmind_nav_lcas: 1.0.9-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.1.1-0`:
- previous version for package: `0.1.0-0`
```
```
- No changes

uol_cmp9767m: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_recovery_behaviours` to `0.1.0-0`:
- upstream repository: https://github.com/strands-project/strands_recovery_behaviours.git
- release repository: https://github.com/strands-project-releases/strands_recovery_behaviours.git
- No changes
- No changes
```
* Update help_screen.py
* Contributors: Bruno Lacerda
```
```
* tidying
* Merge pull request #59 <https://github.com/strands-project/strands_recovery_behaviours/issues/59> from bfalacerda/hydro-devel
christian's magic sequence for restarting motors
* christian's magic sequence for restarting motors
* Contributors: Bruno Lacerda, Nick Hawes
```
```
* tidying
* Contributors: Bruno …
```

strands_recovery_behaviours: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.0.6-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

tradr_uol: 1.0.6-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.0.7-0`:
- previous version for package: `1.0.6-0`
```
* Merge pull request #3 <https://github.com/LCAS/tradr_uol/issues/3> from LCAS/pcl_c11
Package.xml have been updated
* Merge with master
```
- No changes
- No changes
```
* Merge pull request #3 <https://github.com/LCAS/tradr_uol/issues/3> from LCAS/pcl_c11
Package.xml have been updated
* Merge with master
```
- No changes
- No changes
- No changes
```
* Merge pull request #3 …
```

tradr_uol: 1.0.7-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_apps` to `0.2.0-0`:
- upstream repository: https://github.com/strands-project/scitos_apps.git
- release repository: https://github.com/strands-project-releases/scitos_apps.git
- previous version for package: `0.1.2-0`
- No changes
- No changes
- No changes
- No changes
```
* TKrajnik modifications: parameters for gains and ptu velocity (#164 <https://github.com/strands-project/scitos_apps/issues/164>)
* Contributors: francescodelduchetto
```
- No changes
```
```
- No changes
```
* adjusted version
* Merge pull request #162 <https://github.com/strands-project/scitos_apps/issues/162> from …
```

scitos_apps: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rasberry` to `0.1.0-0`:
```
* new_work
* w.i.p.
* Contributors: ThomasDegallaix, adambinch
```
```
* Merge pull request #156 <https://github.com/LCAS/RASberry/issues/156> from gpdas/uv_updates
Tested in simulation. Merging this.
* rasberry_uv updates + minor changes elsewhere
1. sim_riseholme-uv.yaml tmule config is removed and riseholme-uv.yaml can be used for both the physical robot as well as simulation
2. config file (rasberry_uv/config/riseholme.yaml) for configuring which rows have to be treated and start …
```

rasberry: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.0.8-0`:
- previous version for package: `1.0.7-0`
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
* Renaming install libraries
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
``` …
```

tradr_uol: 1.0.8-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.2.0-0`:
```
* added sprayer (#15 <https://github.com/LCAS/CMP9767M/issues/15>)
* added sprayer
* added sprayer into model
* textures with alpha and better lighting
```
- No changes

uol_cmp9767m: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.0.9-0`:
- previous version for package: `1.0.8-0`
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
* Contributors: …
```

tradr_uol: 1.0.9-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.0.10-0`:
- previous version for package: `1.0.9-0`
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
* Fix licenses
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol …
```

tradr_uol: 1.0.10-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.0.5-0`:
```
* Merge branch 'no_dropping'
* date
* fixed clearing buffer
* Merge pull request #7 <https://github.com/marc-hanheide/slackeros/issues/7> from marc-hanheide/no_dropping
no dropping of messages in throttling
* no dropping of messages in throttling
```

slackeros: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.0.11-0`:
- previous version for package: `1.0.10-0`
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
```
```
* Merge branch 'master' of https://github.com/LCAS/tradr_uol
* …
```

tradr_uol: 1.0.11-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.1.0-0`:
```
* Merge pull request #9 <https://github.com/marc-hanheide/slackeros/issues/9> from marc-hanheide/no_dropping
massive refactoring and queue processing
* massive refactoring and queue processing
```

slackeros: 0.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_executive` to `1.2.4-0`:
- previous version for package: `1.2.1-0`
```
* Merge pull request #306 <https://github.com/strands-project/strands_executive/issues/306> from strands-project/marc-hanheide-patch-1
making time-critical tasks a parameter
* making time-critical tasks a parameter
* merge
* Contributors: Marc Hanheide, Nick Hawes
```
```
* merge
```
```
* merge
```
```
* merge
```
```
* merge …
```

strands_executive: 1.2.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.2.2-1`:
- bloom version: `0.6.9`
```
* cleanup in package.xml
```
```
* added argument in localization_local.launch to kill publication of tf transform
* holonomic robot
* cleanup in package.xml
* added license
* removed dep on razor imu
* Cleaned up thorvald_2dnav and created more sensible launch files
* Changed from using positions to velocities for odom and added slash to tf prefix
* removed 'greenhouse' costmap layer
* Contributors: adambinch, larsgrim
```
```
* odom tf params and defaults …
```

thorvald: 0.2.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `0.2.0-0`:
- bloom version: `0.6.9`
- previous version for package: `0.1.18-0`

lcas_teaching: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sentor` to `2.0.1-0`:
- bloom version: `0.6.9`
```
* Merge pull request #1 <https://github.com/LCAS/sentor/issues/1> from LCAS/2.0
Merging 2.0 into master with some modifications for release
* prepare for installation
* prettier prints and longer sleep in loop to avoid None in hz
* added timeout for lambdas and not published
* first commmit version 2.0: yaml file for configuration, singaling also for published, lambda funcs are specified in the yaml as a string
* ehm
* remove logs …
```

sentor: 2.0.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_hri` to `0.2.4-0`:
- upstream repository: https://github.com/strands-project/strands_hri.git
- release repository: https://github.com/strands-project-releases/strands_hri.git
- bloom version: `0.7.1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_hri: 0.2.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `gazebo_contact_monitor` to `1.1.0-0`:
- upstream repository: https://github.com/LCAS/gazebo-contactMonitor.git
- release repository: https://github.com/lcas-releases/gazebo-contactMonitor.git
- previous version for package: `1.0.0-0`
```
* Topic namess follow the CCA rules. Added an error msg and 1s delay if no gz topic is found
* New README. Extra parameters added
Added missing build dependence
```

gazebo_contact_monitor: 1.1.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `gazebo_contact_monitor` to `1.1.1-0`:
- upstream repository: https://github.com/LCAS/gazebo-contactMonitor.git
- release repository: https://github.com/lcas-releases/gazebo-contactMonitor.git
- previous version for package: `1.1.0-0`
```
* Added CMake rule to install launch scripts
```

gazebo_contact_monitor: 1.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `tf_bag` to `0.1.1-0`:
- upstream repository: https://github.com/LCAS/tf_bag.git
- release repository: https://github.com/lcas-releases/tf_bag.git
- bloom version: `0.6.9`
```
* Changes for proper install
* Added install option
* Corrected package name in docs
Fixes #3 <https://github.com/LCAS/tf_bag/issues/3>
* Merge pull request #2 <https://github.com/LCAS/tf_bag/issues/2> from gondsm/master
Make tf_bag compatible with bags recorded with "tf" and "/tf" as topic names
Fixes #1 <https://github.com/LCAS/tf_bag/issues/1>
* Make tf_bag compatible with bags recorded with "tf" and "/tf" as topic names.
* Fix double use of iterator in …
```

tf_bag: 0.1.1-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `robot_blockly` to `0.1.2-0`:
- upstream repository: https://github.com/LCAS/robot_blockly.git
- release repository: https://github.com/strands-project-releases/robot_blockly.git
```
* added
* Merge pull request #5 <https://github.com/LCAS/robot_blockly/issues/5> from LCAS/new_operators
New operators
* new scheme
* first improvements
* updated distance sensor blocks and compressed files
* syntax fix for distance sensor block
* changed distance sensor block, and compressed files
* adding manual start of wicd-daemon (not sure why necessary)
* reducing need for manual interaction
* update of setup script for networking setup
* adding crontab …
```

robot_blockly: 0.1.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.2.2-2`:
- previous version for package: `0.2.2-1`
```
* cleanup in package.xml
```
```
* added argument in localization_local.launch to kill publication of tf transform
* holonomic robot
* cleanup in package.xml
* added license
* removed dep on razor imu
* Cleaned up thorvald_2dnav and created more sensible launch files
* Changed from using positions to velocities for odom and added slash to tf prefix
* removed 'greenhouse' costmap layer
* Contributors: adambinch, larsgrim
```
```
* odom tf params and defaults …
```

thorvald: 0.2.2-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `0.2.3-0`:
- previous version for package: `0.2.2-2`
```
* changelogs
```
```
* changelogs
```
```
* changelogs
* Merge pull request #57 <https://github.com/LCAS/Thorvald/issues/57> from larsgrim/kinetic-devel
Support for new batteries and some simple gui tweaks
* moved motor controller modes to CanDriveItf to avoid dep on thorvald_base
* added motor controller modes to msg
* added support for 2.gen KC batteries
* Contributors: Marc Hanheide, larsgrim
* Merge pull request #57 …
```

thorvald: 0.2.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sentor` to `2.0.3-0`:
- previous version for package: `2.0.1-0`
```
* Merge pull request #3 <https://github.com/LCAS/sentor/issues/3> from francescodelduchetto/master
fix some bugs
* Merge branch 'master' into master
* Merge branch 'master' of https://github.com/francescodelduchetto/sentor
* fix various errors
* Contributors: Lindsey User, Marc Hanheide
```

sentor: 2.0.3-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.2.0-0`:
- previous version for package: `0.1.6-0`
```
* Adding hierarchical planning node
* Adding a KinematicCarStateSpace to better handle different steering functions
* Adding Bidirectional-RRTSTAR
```

iliad_smp: 0.2.0-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_ros` to `2.2.5-0`:
- previous version for package: `2.2.4-0`
- No changes
- No changes

realsense_ros: 2.2.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_perception_people` to `1.8.1-1`:
- previous version for package: `1.8.0-0`
```
* Message type change. (#225 <https://github.com/strands-project/strands_perception_people/issues/225>)
* Peoplestamped.msg added for cellphone GPS data. Composed of an array of PersonStamped.msg
* People msg chsnged to PeopleStamped message
* People msg changed to PeopleStamped msg
* code cleaned
* people_msgs dependency added
* Now supports both People and PeopleStamped msg types
* Contributors: Khan
```
```
* …
```

strands_perception_people: 1.8.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_ros` to `2.2.6-1`:
- previous version for package: `2.2.5-0`
- No changes
```
* Merge pull request #2 <https://github.com/LCAS/realsense/issues/2> from IntelRealSense/development
pull from upstream
* add note to rs_rgbd.launch, reminding users to initially install ros package rgbd_launch.
* Merge branch 'fix_t265_coordinates' into development
* removed global variable _device, based on @akirayou at https://github.com/IntelRealSense/realsense-ros/issues/774#issuecomment-494236047
* Merge branch 'dense_pointcloud' into development
* Merge …
```

realsense_ros: 2.2.6-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.2.2-1`:
```
* Allowing CLiFF-based sampler to read the map from the service
```

iliad_smp: 0.2.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.2.0-1`:
- previous version for package: `0.1.0-0`
```
* Merge pull request #11 <https://github.com/marc-hanheide/slackeros/issues/11> from francescodelduchetto/master
Uploading an image with each message sent
* parameter for img upload channels and take channel from payload when using slash command
* putting some try catches and parameter names
* fix missing parameters to be passed to ImageUPloader
* automatically select the encoding from the image msg
* possibility of uploading an image in the administration channel every …
```

slackeros: 0.2.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ouster` to `0.1.2-1`:
```
* Merge pull request #3 <https://github.com/LCAS/ouster_example/issues/3> from LCAS/scosar-dev
Included roscpp in package.xml
* Included roscpp to package.xml of ouster_client
* Fix header dependencies
* Typo in CMakelist
* Fix CMakelist of ouster_client
```
```
* Fix header dependencies
* Added tf2_geometry_msgs in CMakelist and package.xml
* Fix tf2 error in build
* Remove visualization example code and Fix timestamp problem
* Remove …
```

ouster: 0.1.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ouster` to `0.1.3-1`:
- previous version for package: `0.1.2-1`
```
* removed devel check
```
- No changes

ouster: 0.1.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ouster` to `0.1.4-1`:
- previous version for package: `0.1.3-1`
```
* Uncomment a line in CMakeLists
* Contributors: scosar
```
- No changes

ouster: 0.1.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ouster` to `0.1.5-1`:
- previous version for package: `0.1.4-1`
- No changes
```
* Merge pull request #4 <https://github.com/LCAS/ouster_example/issues/4> from LCAS/scosar-dev
Fix missing launch file
* Fix missing launch file
```

ouster: 0.1.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ouster` to `0.1.6-1`:
- previous version for package: `0.1.5-1`
- No changes
```
* Merge pull request #5 <https://github.com/LCAS/ouster_example/issues/5> from LCAS/scosar-dev
Fix missing executables
* Fix executable paths
* Fix missing executables
```

ouster: 0.1.6-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.2.1-1`:
- previous version for package: `0.2.0-1`
```
* Merge pull request #12 <https://github.com/marc-hanheide/slackeros/issues/12> from marc-hanheide/format_and_name
Format and name
* identify author as hostname
* mostly formatting
```

slackeros: 0.2.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `1.0.8-1`:
- previous version for package: `1.0.7-0`
```
* Merge branch 'indigo-devel' of https://github.com/strands-project/strands_navigation into indigo-devel
* Merge pull request #369 <https://github.com/strands-project/strands_navigation/issues/369> from strands-project/ori-indigo-devel
Support for multi-robot and different global planners
* Fixed typo and maintaining backward compatibility for policy visualisation
* Merge remote-tracking branch 'ori/indigo-devel' into indigo-devel …
```

strands_navigation: 1.0.8-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.1.0-1`:
- previous version for package: `1.0.2-1`
- No changes
- No changes
- No changes
```
* Merge pull request #67 <https://github.com/LCAS/Thorvald/issues/67> from c-small/kinetic-devel
Tall robot simulation
* Tall robot files
* Contributors: Jaime Pulido Fentanes, c-small
```
- No changes
```
* Merge pull request #67 <https://github.com/LCAS/Thorvald/issues/67> from c-small/kinetic-devel
Tall robot simulation
* Tall robot files
* Contributors: Jaime Pulido Fentanes, c-small
```
```
* Merge pull request #67 …
```

thorvald: 1.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `0.0.4-0`:
```
* Very few minor updates
```
```
* First CLiFFmap RViz Plugin. Also the best.
```

mod_ros: 0.0.4-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `0.0.5-0`:
```
* Remove dependencies for pedsim_scenarios
* Contributors: Chittaranjan Srinivas Swaminathan, Chittaranjan Swaminathan
```
```
* STeF-map ROS is now part of MoD ROS package.
* Contributors: Chittaranjan Srinivas Swaminathan, Chittaranjan Swaminathan
```

mod_ros: 0.0.5-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `0.0.2-0`:
```
* Add install targets
* Move MoD to separate package. STeFMap planning works.
* Contributors: Chittaranjan Srinivas Swaminathan, Chittaranjan Swaminathan
```
```
* Fix bugs. Small info improvements.
* Add ncfm maps
* Adjust licenses
* Refactoring - further
* Contributors: Chittaranjan Srinivas Swaminathan, Chittaranjan Swaminathan
```

ompl_planners: 0.0.2-0 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_detector` to `0.0.3-1`:
- upstream repository: https://github.com/LCAS/pcl_detector.git
- release repository: https://github.com/lcas-releases/pcl_detector.git
```
* Merge pull request #3 <https://github.com/LCAS/pcl_detector/issues/3> from scosar/master
Input parameter to set lidar topic
* Merge remote-tracking branch 'upstream/master'
* Included a parameter to set input lidar topic
```

pcl_detector: 0.0.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `0.0.6-1`:
```
* Add eigen to package.xml
```
- No changes
- No changes
- No changes
- No changes

mod_ros: 0.0.6-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `0.0.3-1`:
```
* Add eigen as dependency
```
```
* Add mrpt as dependency
```

ompl_planners: 0.0.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `0.0.4-1`:
- previous version for package: `0.0.3-1`
```
* Fix ompl dependency
```
```
* Fix ompl dependency
```

ompl_planners: 0.0.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `0.0.7-1`:
- previous version for package: `0.0.6-1`
```
* Add parameters for topic, service and frame names
```
- No changes
- No changes
- No changes
- No changes

mod_ros: 0.0.7-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_ros` to `2.2.6-2`:
- previous version for package: `2.2.6-1`
- No changes
```
* Merge pull request #2 <https://github.com/LCAS/realsense/issues/2> from IntelRealSense/development
pull from upstream
* add note to rs_rgbd.launch, reminding users to initially install ros package rgbd_launch.
* Merge branch 'fix_t265_coordinates' into development
* removed global variable _device, based on @akirayou at https://github.com/IntelRealSense/realsense-ros/issues/774#issuecomment-494236047
* Merge branch 'dense_pointcloud' into development
* Merge …
```

realsense_ros: 2.2.6-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `0.0.5-1`:
- previous version for package: `0.0.4-1`
- No changes
```
* Add compile options for external literals
```

ompl_planners: 0.0.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `0.0.6-1`:
- previous version for package: `0.0.5-1`
```
* Fix install target error
```
```
* Fix install target for param folder.
```

ompl_planners: 0.0.6-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.3.0-1`:
- previous version for package: `0.2.2-1`
```
* Including DownWithCLiFF objective functions
```

iliad_smp: 0.3.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.1.1-1`:
- previous version for package: `1.1.0-1`
- No changes
- No changes
```
* Merge pull request #71 <https://github.com/LCAS/Thorvald/issues/71> from LCAS/marc-hanheide-patch-1
make rate configurable
* make rate configurable
The idea is to make the publish rate configurable
* Merge pull request #69 <https://github.com/LCAS/Thorvald/issues/69> from larsgrim/kinetic-devel
Battery status, GUI mods, missing installs
* added status to battery
* Contributors: Marc Hanheide, larsgrim
```
- No changes
```
* Merge pull request #69 …
```

thorvald: 1.1.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.1.2-1`:
- previous version for package: `1.1.1-1`
- No changes
- No changes
```
* fixed stupid bug
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

thorvald: 1.1.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `optis_drivers` to `1.1.2-1`:
- upstream repository: https://github.com/LCAS/optris_drivers.git
- release repository: https://github.com/lcas-releases/optis_drivers.git
```
* more deps
* more deps
* added udev as a hack to work around broken irlibimager
```

optis_drivers: 1.1.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_detector` to `0.0.3-2`:
- upstream repository: https://github.com/LCAS/pcl_detector.git
- release repository: https://github.com/lcas-releases/pcl_detector.git
- previous version for package: `0.0.3-1`
```
* Merge pull request #3 <https://github.com/LCAS/pcl_detector/issues/3> from scosar/master
Input parameter to set lidar topic
* Merge remote-tracking branch 'upstream/master'
* Included a parameter to set input lidar topic
```

pcl_detector: 0.0.3-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_distribution` to `0.1.0-2`:
- previous version for package: `0.0.8-0`
```
* update coordination config file
* Merge branch 'master' of https://gitsvn-nt.oru.se/iliad/software/iliad_metapackage
* Fixes
* change in coordinator.yaml
* Fix for bt launch
* Some changes to bt launch scripts
* Move calib file to right location
* Add proper robot6.yaml
* Delete robot6.yaml
* Merge branch 'bt-wip' of gitsvn-nt.oru.se:iliad/software/iliad_metapackage
* Fix floor laser topic again
* changed prefix of reflex topics
* …
```

iliad_distribution: 0.1.0-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `um7` to `0.0.6-1`:
- upstream repository: https://github.com/LCAS/um7.git
- release repository: https://github.com/lcas-releases/um7.git
```
* fix deps
* Merge pull request #1 <https://github.com/LCAS/um7/issues/1> from MikHut/fix_enu_tf_lcas
Fix enu tf
* add maintainer
* install target for launch file
* added launch file
* fix enu tf error and add param for yaw offset
* Fixed linter errors.
* Contributors: Jaime Pulido Fentanes, Marc Hanheide, MikHut, Tony Baltovski
```

um7: 0.0.6-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_ros` to `2.2.6-3`:
- previous version for package: `2.2.6-2`
- No changes
```
* Merge pull request #2 <https://github.com/LCAS/realsense/issues/2> from IntelRealSense/development
pull from upstream
* add note to rs_rgbd.launch, reminding users to initially install ros package rgbd_launch.
* Merge branch 'fix_t265_coordinates' into development
* removed global variable _device, based on @akirayou at https://github.com/IntelRealSense/realsense-ros/issues/774#issuecomment-494236047
* Merge branch 'dense_pointcloud' into development
* Merge …
```

realsense_ros: 2.2.6-3 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.1.3-1`:
- previous version for package: `1.1.2-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge pull request #72 <https://github.com/LCAS/Thorvald/issues/72> from Jailander/kinetic-devel
fixes frame for tall robot
* fixes frame for tall robot
* Contributors: Jaime Pulido Fentanes, jailander
```
- No changes
- No changes
- No changes
- No changes
```
* added config for xbox one controller
```
- No changes

thorvald: 1.1.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.3.0-1`:
```
* fixed new thorvald (#37 <https://github.com/LCAS/CMP9767M/issues/37>)
* Tutorial9 (#22 <https://github.com/LCAS/CMP9767M/issues/22>)
* tutorial9 files
* fixes
* fixes 2
* adding robot frame prefix to config files
* using amcl instead of fake localization
* improve simulation performance
* Fix greg (#17 <https://github.com/LCAS/CMP9767M/issues/17>)
* Moved workshop files into a single repo
* Dependency fixes
* Nodelet/PCL dependency fix
* Fixed warning: package uol_cmp9767m_base …
```

uol_cmp9767m: 0.3.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `kmo_interfaces` to `0.1.0-1`:
- upstream repository: https://gitsvn-nt.oru.se/marc-hanheide/kmo_interfaces.git
- release repository: https://github.com/iliad-project/kmo_interfaces-release.git
```
* Merge branch 'master' of https://gitsvn-nt.oru.se/software/kmo_interfaces
* Merge branch 'master' of https://gitsvn-nt.oru.se/ksatyaki/kmo_interfaces
* Merge branch 'master' of gitsvn-nt.oru.se:software/kmo_interfaces
* Merge branch 'master' into 'master'
Some missing dependencies and version numbering used in the release process
See merge request !1
* Added bt truck test program for fork sensors.
* Added host port access functions.
* Added …
```

kmo_interfaces: 0.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `1.0.0-1`:
- previous version for package: `0.0.7-1`
```
* Bug fixes. CLiFF-map p and q values were not read properly before.
```
```
* GMMT-map (Bennewitz et al. - Learning motion patterns of people...)
* Contributors: Chittaranjan Swaminathan, Johan Feinestam
```
```
* Added an rviz plugin for gmmtmaps
```

mod_ros: 1.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `1.0.0-1`:
- previous version for package: `0.0.6-1`
```
* Modify upstream criterion objective to use GMMT-map, optionally
```
```
* Add more maps
* GMMT planning works
```

ompl_planners: 1.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.4.0-1`:
- previous version for package: `0.3.0-1`
```
* multiple robots
* bug fix
* Friction
```
```
* added working mover
* more examples
```

uol_cmp9767m: 0.4.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.4.1-1`:
- previous version for package: `0.4.0-1`
```
* added rviz and fixed frames for rviz (and map)
```
- No changes

uol_cmp9767m: 0.4.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rgbd_gpu_detector` to `2.0.3-1`:
- previous version for package: `2.0.3-0`
```
* Fix error message due to missing nodelet_plugins.xml
```

rgbd_gpu_detector: 2.0.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.7-1`:
- previous version for package: `1.0.6-0`
```
* Fix typo
* Update install targets
* Merge branch 'master' of https://gitsvn-nt.oru.se/iliad/software/iliad_human_perception
* Merge branch 'master' of https://gitsvn-nt.oru.se/iliad/software/iliad_human_perception
* modifies CMakeList for new reflex node
* modifies reflex script to reuse TF from incoming msg
* new script for reflex_to_detected_persons
* Updates to person detection pipeline
* Do not delete …
```

iliad_human_perception: 1.0.7-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rgbd_gpu_detector` to `2.0.4-1`:
- previous version for package: `2.0.3-0`
```
* Parametrize params
* Parametrize backward shift, default to 0 (better according to Narunas' experiments)
```

rgbd_gpu_detector: 2.0.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.10-1`:
- previous version for package: `1.0.7-1`
- No changes
```
* Change dependency name
```

iliad_human_perception: 1.0.10-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.3.1-1`:
- previous version for package: `0.3.0-1`
```
* Adding modality parameter to select the planner from the hierarchical planning node (i.e. 0 means hierarchical, 1 for SMP, 2 for lattice).
```

iliad_smp: 0.3.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.11-1`:
- previous version for package: `1.0.10-1`
- No changes
```
* Add missing nav_msgs dependency
```

iliad_human_perception: 1.0.11-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.12-1`:
- previous version for package: `1.0.11-1`
- No changes
```
* Add OpenCV dependency
```

iliad_human_perception: 1.0.12-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.16-1`:
- previous version for package: `1.0.12-1`
- No changes
```
* Add missing install targets
```

iliad_human_perception: 1.0.16-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rgbd_gpu_detector` to `2.0.5-1`:
- previous version for package: `2.0.4-1`
```
* Change INFO logging messages which reoccur every frame into DEBUG
```

rgbd_gpu_detector: 2.0.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `franka_ros_lcas` to `0.8.0-1`:
- upstream repository: https://github.com/LCAS/franka_ros.git
- release repository: https://github.com/lcas-releases/franka_ros.git

franka_ros_lcas: 0.8.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.4.2-1`:
- previous version for package: `0.4.1-1`
```
* new cropweed models (#40 <https://github.com/LCAS/CMP9767M/issues/40>)
* Removed map_server from test
* Contributors: Marc Hanheide, gcielniak
```
```
* added tf_listener
```

uol_cmp9767m: 0.4.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_human_perception` to `1.0.18-1`:
- previous version for package: `1.0.17-1`
- No changes
```
* Set modality and covariance correctly for tracking to work
```

iliad_human_perception: 1.0.18-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `rosbridge_suite_lcas` to `0.12.0-1`:
- upstream repository: https://github.com/LCAS/rosbridge_suite.git
- release repository: https://github.com/lcas-releases/rosbridge_suite.git
```
* Revert "changelogs"
This reverts commit bfc023af331ee980c558858fb03cfdb8db929a7a.
* Revert "0.12.0"
This reverts commit 27426b196eb0f88ce26fecd52b0d07211b54071d.
* 0.12.0
* changelogs
* Fix rosapi get_action_servers (#429 <https://github.com/LCAS/rosbridge_suite/issues/429>)
The currently used proxy.get_topics function does not exists and results in the following error: "AttributeError: 'module' object has no attribute 'get_topics'n" …
```

rosbridge_suite_lcas: 0.12.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.4.3-1`:
- previous version for package: `0.4.2-1`
```
* Assmnt1920 (#41 <https://github.com/LCAS/CMP9767M/issues/41>)
* new cropweed models
* fixed texture height
* Contributors: gcielniak
```
- No changes

uol_cmp9767m: 0.4.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.5.0-1`:
- previous version for package: `0.4.3-1`
```
* adding a walker into the simulation (#39 <https://github.com/LCAS/CMP9767M/issues/39>)
* actor with plugin
* arguments to launch world with obstacles
```
- No changes

uol_cmp9767m: 0.5.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.5.1-1`:
- previous version for package: `0.5.0-1`
```
* added switches for fake localisation (#42 <https://github.com/LCAS/CMP9767M/issues/42>)
* added switches for fake localisation
* fixed test for new tf switch
```
- No changes

uol_cmp9767m: 0.5.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_oru` to `1.5.5-1`:
- upstream repository: https://github.com/dan11003/velodyne_pointcloud_oru
- release repository: https://github.com/LCAS/velodyne-release.git
- previous version for package: `1.2.1-0`
```
* Update cloud_node_vlp16_hz.test
reduced minimum frequency required.
* Update cloud_nodelet_32e_hz.test
reduced minimum frequency requirement for unit test
* updated tests
* updated name in unit tests
* Contributors: dan11003, daniel
```

velodyne_oru: 1.5.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ndt_core` to `2.3.0-1`:
- upstream repository: https://gitsvn-nt.oru.se/software/ndt_core.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/releases/ndt_core-release.git
- previous version for package: `2.0.0-0`

ndt_core: 2.3.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ndt_tools` to `2.0.2-1`:
- upstream repository: https://gitsvn-nt.oru.se/software/ndt_tools.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/releases/ndt_tools-release.git
- previous version for package: `2.0.0-0`
- No changes
- No changes
- No changes
- No changes
- No changes

ndt_tools: 2.0.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `sandbox` to `0.0.14-1`:
- upstream repository: https://github.com/LCAS/sandbox.git
- release repository: https://github.com/LCAS/sandbox-release.git
- No changes

sandbox: 0.0.14-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `1.3.0-1`:
- No changes
- No changes
- No changes
```
* changed gazebo for melodic
```
- No changes
```
* changed gazebo for melodic
```
- No changes
```
* making code base the same for kinetic and melodic (#89 <https://github.com/LCAS/Thorvald/issues/89>)
* removed old gazebo plugin and adaptation for gazebo9+ (#87 <https://github.com/LCAS/Thorvald/issues/87>)
* changed gazebo for melodic
```
- No changes
- No …

thorvald: 1.3.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `rosduct` to `0.0.6-1`:
```
* Fix: ROSDuctConnection() object's latch attribute not set (#5 <https://github.com/LCAS/rosduct/issues/5>)
* Fix for missing latch for local and remote topics - in ROSDuctConnection objects
Setting the default value of msg.latch for local and remote topics to False
If the latch value is given in the config (takes up to 4 values for topics), that value is taken
* msg.latch takes string or bool values for local and remote topics
Fix in check_if_msgs_are_installed() when local_topics …
```

rosduct: 0.0.6-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bayes_tracking` to `1.4.0-1`:
```
* added pruneNamedTracks (#25 <https://github.com/LCAS/bayestracking/issues/25>)
* fixed tag check for LABELED
* added pruneNamedTracks
* removed print
* pruning now works
```

bayes_tracking: 1.4.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `acado` to `1.2.3-1`:
- upstream repository: https://github.com/LCAS/acado.git
- release repository: https://github.com/LCAS/acado_release.git
```
* added missing package.xml
* Merge pull request #161 <https://github.com/LCAS/acado/issues/161> from clearpathrobotics/CORE-1683_spam_fix
Commented out a message that gets displayed even when PRINTLEVEL is set to NONE
* minor update lifted adjoint integrator
* correction of the adjoint term
* removed the option LIFTED_INTEGRATOR_MODE
* implemented INIS scheme with adjoint correction
* adjoint exact Hessian solver
* fixed bug regarding gradient update in exact Hessian RTI
* adjoint gradient …
```

acado: 1.2.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `catkin_simple` to `0.2.0-1`:
- upstream repository: https://github.com/LCAS/catkin_simple.git
- release repository: https://github.com/lcas-releases/catkin_simple.git
```
* Merge pull request #27 <https://github.com/catkin/catkin_simple/issues/27> from flaviofontana/patch-1
add dynamic reconfigure info to the readme
* add dynamic reconfigure info to the readme
* Merge pull request #26 <https://github.com/catkin/catkin_simple/issues/26> from flaviofontana/add_dynamic_reconfigure
added autodetection of dynamic_reconfigure
* fixed indentation
* adding build dependency on gencfg
* adding all cfg all files at once
* added autodetection of …
```

catkin_simple: 0.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_ros` to `2.3.0-1`:
```
* disable testing
```
```
```

realsense_ros: 2.3.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_ros` to `2.3.0-1`:
- previous version for package: `2.2.6-3`
```
* disable testing
```
```
```

realsense_ros: 2.3.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `robot_pose_publisher` to `0.2.4-1`:
- upstream repository: https://github.com/GT-RAIL/robot_pose_publisher.git
- release repository: https://github.com/lcas-releases/robot_pose_publiser.git
```
* fixed dox file
* fixed readme
* travis edit
* Contributors: David Kent, Russell Toris
```

robot_pose_publisher: 0.2.4-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_common` to `0.1.12-1`:
- upstream repository: https://github.com/strands-project/scitos_common.git
- release repository: https://github.com/strands-project-releases/scitos_common.git
- No changes
- No changes
- No changes

scitos_common: 0.1.12-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `velodyne_oru` to `1.5.5-1`:
- upstream repository: https://github.com/dan11003/velodyne_pointcloud_oru
- release repository: https://github.com/LCAS/velodyne-release.git
```
* Update cloud_node_vlp16_hz.test
reduced minimum frequency required.
* Update cloud_nodelet_32e_hz.test
reduced minimum frequency requirement for unit test
* updated tests
* updated name in unit tests
* Contributors: dan11003, daniel
```

velodyne_oru: 1.5.5-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `steering_functions` to `1.0.5-1`:
- upstream repository: https://github.com/iliad-project/steering_functions.git
- release repository: https://github.com/lcas-releases/steering_functions.git
```
* install everything in headers
```

steering_functions: 1.0.5-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `sentor` to `2.0.3-1`:
```
* Merge pull request #3 <https://github.com/LCAS/sentor/issues/3> from francescodelduchetto/master
fix some bugs
* Merge branch 'master' into master
* Merge branch 'master' of https://github.com/francescodelduchetto/sentor
* fix various errors
* Contributors: Lindsey User, Marc Hanheide
```

sentor: 2.0.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `sicks300` to `1.2.1-1`:
- upstream repository: https://github.com/strands-project/sicks300.git
- release repository: https://github.com/strands-project-releases/sicks300.git
- No changes

sicks300: 1.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `persistent_topics` to `1.5.2-1`:
- upstream repository: https://github.com/marc-hanheide/persistent_topics.git
- release repository: https://github.com/lcas-releases/persistent_topics.git
- No changes

persistent_topics: 1.5.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `marvelmind_nav_lcas` to `1.0.9-1`:
- upstream repository: https://github.com/LCAS/ros_marvelmind_package.git
- release repository: https://github.com/lcas-releases/ros_marvelmind_package.git
```
* ROS_INFOs along with topic publish are disabled
* added install targets
* Contributors: Marc Hanheide, gpdas, thorvald
```

marvelmind_nav_lcas: 1.0.9-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.5.2-1`:
- previous version for package: `0.5.1-1`
```
* Merge branch 'master' into mapping
* Contributors: gcielniak
```
```
* Merge pull request #44 <https://github.com/LCAS/CMP9767M/issues/44> from LCAS/mapping
Additional files for workshop 8. AMCL launch can now accept robot_name as a parameter.
* Merge branch 'master' into mapping
* Additional files for workshop 8. AMCL launch can now accept robot_name as a parameter.
* Merge pull request #43 <https://github.com/LCAS/CMP9767M/issues/43> from LCAS/w7_1920
space fix planners
* …
```

uol_cmp9767m: 0.5.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `twitter_bootstrap` to `0.0.3-1`:
- upstream repository: https://github.com/strands-project/twitter_bootstrap.git
- release repository: https://github.com/strands-project-releases/twitter_bootstrap.git

twitter_bootstrap: 0.0.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `um7` to `0.0.6-1`:
- upstream repository: https://github.com/LCAS/um7.git
- release repository: https://github.com/lcas-releases/um7.git
```
* fix deps
* Merge pull request #1 <https://github.com/LCAS/um7/issues/1> from MikHut/fix_enu_tf_lcas
Fix enu tf
* add maintainer
* install target for launch file
* added launch file
* fix enu tf error and add param for yaw offset
* Fixed linter errors.
* Contributors: Jaime Pulido Fentanes, Marc Hanheide, MikHut, Tony Baltovski
```

um7: 0.0.6-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_webtools` to `0.1.0-1`:
- upstream repository: https://github.com/strands-project/strands_webtools.git
- release repository: https://github.com/strands-project-releases/strands_webtools.git
```
* changed mjpeg_server to web_video_server
```

strands_webtools: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_ui` to `0.2.1-1`:
- upstream repository: https://github.com/strands-project/strands_ui.git
- release repository: https://github.com/strands-project-releases/strands_ui.git
```
* Merge pull request #109 <https://github.com/strands-project/strands_ui/issues/109> from francescodelduchetto/pull-req
fix global variable declaration missing
* fix global variable declaration missing
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_ui: 0.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_drivers` to `0.2.0-1`:
- upstream repository: https://github.com/strands-project/scitos_drivers.git
- release repository: https://github.com/strands-project-releases/scitos_drivers.git
```
* changelogs
* changed maintainer from Chris to Marc
* changed maintainer from Chris to Marc
```
```
* removed odometry_mileage as it caused a cyclic dependency
* changelogs
```
```
* changelogs
* changed maintainer from Chris to Marc
* changed maintainer from Chris to Marc
```
```
* added qt4 dep
* …
```

scitos_drivers: 0.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `whycon` to `0.2.4-1`:
- upstream repository: https://github.com/LCAS/whycon.git
- release repository: https://github.com/strands-project-releases/whycon.git
```
* fixed dependencies
* added id generator
* imported snapcart version
```

whycon: 0.2.4-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `whycon` to `2.3.0-1`:
- upstream repository: https://github.com/LCAS/whycon.git
- release repository: https://github.com/strands-project-releases/whycon.git
- previous version for package: `0.2.4-1`
```
* 0.2.4
* changelog
* fixed dependencies
* added id generator
* imported snapcart version
```

whycon: 2.3.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `whycon` to `2.3.0-1`:
- upstream repository: https://github.com/LCAS/whycon.git
- release repository: https://github.com/strands-project-releases/whycon.git
```
* 0.2.4
* changelog
* fixed dependencies
* added id generator
* imported snapcart version
```

whycon: 2.3.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `libfreenect2` to `0.1.0-1`:
- upstream repository: https://github.com/LCAS/libfreenect2.git
- release repository: https://github.com/lcas-releases/libfreenect2.git
- previous version for package: `0.0.9-0`
```
* Merge pull request #3 <https://github.com/LCAS/libfreenect2/issues/3> from LCAS/new
Pulled upstream and made more general for cuda
* Fixed cuda
* new cuda
* Merge branch 'master' of https://github.com/OpenKinect/libfreenect2 into new
* Update TegraJPEG detection
Use jpeglib.h from /usr/src/tegra_multimedia_api.
Remove old source downloading and Tegra version detection routines.
Remove support for 32-bit platforms (probably TK1).
* Add android build script and …
```

libfreenect2: 0.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `libfreenect2` to `0.1.0-1`:
- upstream repository: https://github.com/LCAS/libfreenect2.git
- release repository: https://github.com/lcas-releases/libfreenect2.git
```
* Merge pull request #3 <https://github.com/LCAS/libfreenect2/issues/3> from LCAS/new
Pulled upstream and made more general for cuda
* Fixed cuda
* new cuda
* Merge branch 'master' of https://github.com/OpenKinect/libfreenect2 into new
* Update TegraJPEG detection
Use jpeglib.h from /usr/src/tegra_multimedia_api.
Remove old source downloading and Tegra version detection routines.
Remove support for 32-bit platforms (probably TK1).
* Add android build script and instructions …
```

libfreenect2: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_drivers` to `0.2.0-2`:
- upstream repository: https://github.com/strands-project/scitos_drivers.git
- release repository: https://github.com/strands-project-releases/scitos_drivers.git
- previous version for package: `0.2.0-1`
```
* changelogs
* changed maintainer from Chris to Marc
* changed maintainer from Chris to Marc
```
```
* removed odometry_mileage as it caused a cyclic dependency
* changelogs
```
```
* changelogs
* changed maintainer from Chris to Marc
* changed maintainer from Chris to Marc
```
```
* added qt4 dep …
```

scitos_drivers: 0.2.0-2 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `openni_wrapper` to `0.1.0-1`:
- upstream repository: https://github.com/strands-project/openni_wrapper.git
- release repository: https://github.com/strands-project-releases/openni_wrapper.git
```
* new export class
```

openni_wrapper: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `scitos_apps` to `0.2.0-1`:
- upstream repository: https://github.com/strands-project/scitos_apps.git
- release repository: https://github.com/strands-project-releases/scitos_apps.git
- No changes
- No changes
- No changes
- No changes
```
* TKrajnik modifications: parameters for gains and ptu velocity (#164 <https://github.com/strands-project/scitos_apps/issues/164>)
* Contributors: francescodelduchetto
```
- No changes
```
```
- No changes
```
* adjusted version
* Merge pull request #162 <https://github.com/strands-project/scitos_apps/issues/162> from …
```

scitos_apps: 0.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.9-1`:
- No changes
```
* Changed readme.md file in kinect2_bridge
```
- No changes
- No changes
- No changes

iai_kinect2: 0.0.9-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_apps` to `0.2.6-1`:
- upstream repository: https://github.com/strands-project/strands_apps.git
- release repository: https://github.com/strands-project-releases/strands_apps.git
```
* always check door before passing
* display arrow while waiting
* updates to use door waiting properly
* reduce required time of seeing the door open for the glass door.
* less confident on open doors when doing door_wait_and_move_base as this action is to be used for glass doors
* Fixing bug when no doors in the environment (#64 <https://github.com/strands-project/strands_apps/issues/64>)
* adding door prediction to install targets
* fixing bug when …
```

strands_apps: 0.2.6-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `slackeros` to `0.2.1-1`:
```
* Merge pull request #12 <https://github.com/marc-hanheide/slackeros/issues/12> from marc-hanheide/format_and_name
Format and name
* identify author as hostname
* mostly formatting
```

slackeros: 0.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `iai_kinect2` to `0.0.10-1`:
- previous version for package: `0.0.9-1`
- No changes
```
* added opencl dep
```
- No changes
```
* added opencl dep
```
- No changes

iai_kinect2: 0.0.10-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_movebase` to `1.0.0-1`:
- upstream repository: https://github.com/strands-project/strands_movebase.git
- release repository: https://github.com/strands-project-releases/strands_movebase.git
- No changes
- No changes
```
```
- No changes
```
* Merge pull request #75 <https://github.com/strands-project/strands_movebase/issues/75> from strands-project/remove_strands_navfn
removed strands_navfn
* removed strands_navfn
```

strands_movebase: 1.0.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_morse` to `0.2.3-1`:
- upstream repository: https://github.com/strands-project/strands_morse.git
- release repository: https://github.com/strands-project-releases/strands_morse.git
```
* Merge pull request #175 <https://github.com/strands-project/strands_morse/issues/175> from francescodelduchetto/kinetic-devel
the collection museum simulation
* simulation scaled according to real-world measures
* better lights for simulation
* the collection museum simulation
```

strands_morse: 0.2.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_morse` to `1.4.2-1`:
- upstream repository: https://github.com/strands-project/morse.git
- release repository: https://github.com/lcas-releases/morse.git

lcas_morse: 1.4.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_morse` to `0.2.3-2`:
- upstream repository: https://github.com/strands-project/strands_morse.git
- release repository: https://github.com/strands-project-releases/strands_morse.git
- previous version for package: `0.2.3-1`
```
* Merge pull request #175 <https://github.com/strands-project/strands_morse/issues/175> from francescodelduchetto/kinetic-devel
the collection museum simulation
* simulation scaled according to real-world measures
* better lights for simulation
* the collection museum simulation
```

strands_morse: 0.2.3-2 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `1.1.0-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'indigo-devel' into fix_route_search
* Merge pull request #376 <https://github.com/strands-project/strands_navigation/issues/376> from gpdas/exec_policy_reconf_edge
enable edge_reconfig for execute_policy_mode server
* removing message_store_map_switcher from dependencies
* Contributors: Jaime Pulido Fentanes, gpdas
```
- No changes
- No changes
```
* Merge …
```

strands_navigation: 1.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.4-1`:
```
* added package.xml and always compile realtime
* Merge pull request #2 <https://github.com/LCAS/py_at_broker/issues/2> from sarkrishnan/master
added additional sensor message capability for sl_panda to python
* added additional sensor message capability for sl_panda to python
* Update readme.rst
added description for compile parameters to py_at_broker build
* Update readme.rst
* Update readme.rst
* Merge pull request #1 <https://github.com/LCAS/py_at_broker/issues/1> from …
```

py_at_broker: 0.0.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.4-1`:
```
* added package.xml and always compile realtime
* Merge pull request #2 <https://github.com/LCAS/py_at_broker/issues/2> from sarkrishnan/master
added additional sensor message capability for sl_panda to python
* added additional sensor message capability for sl_panda to python
* Update readme.rst
added description for compile parameters to py_at_broker build
* Update readme.rst
* Update readme.rst
* Merge pull request #1 <https://github.com/LCAS/py_at_broker/issues/1> from …
```

py_at_broker: 0.0.4-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.5-1`:
- previous version for package: `0.0.4-1`
```
* export and install all headers correctly
```

py_at_broker: 0.0.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.5-1`:
- previous version for package: `0.0.4-1`
```
* export and install all headers correctly
```

py_at_broker: 0.0.5-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.8-1`:
- previous version for package: `0.0.5-1`
```
* lower python version ok
```

py_at_broker: 0.0.8-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.8-1`:
- previous version for package: `0.0.5-1`
```
* lower python version ok
```

py_at_broker: 0.0.8-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.9-1`:
- previous version for package: `0.0.8-1`
```
* added setuptools
```

py_at_broker: 0.0.9-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.9-1`:
- previous version for package: `0.0.8-1`
```
* added setuptools
```

py_at_broker: 0.0.9-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.10-1`:
- previous version for package: `0.0.9-1`
```
* added root
```

py_at_broker: 0.0.10-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.10-1`:
- previous version for package: `0.0.9-1`
```
* added root
```

py_at_broker: 0.0.10-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.12-1`:
- previous version for package: `0.0.10-1`
```
* hack for DESTDIR
```

py_at_broker: 0.0.12-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.13-1`:
- previous version for package: `0.0.12-1`
```
* hack for DESTDIR
```

py_at_broker: 0.0.13-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.13-1`:
- previous version for package: `0.0.10-1`
```
* hack for DESTDIR
```

py_at_broker: 0.0.13-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.14-1`:
- previous version for package: `0.0.13-1`
```
* added message
```

py_at_broker: 0.0.14-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `py_at_broker` to `0.0.14-1`:
- previous version for package: `0.0.13-1`
```
* added message
```

py_at_broker: 0.0.14-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `quadprogpp` to `0.0.2-1`:
- upstream repository: https://github.com/LCAS/QuadProgpp.git
- release repository: https://github.com/lcas-releases/quadprogpp.git
```
* made comileable via catkin
* Merge pull request #12 <https://github.com/LCAS/QuadProgpp/issues/12> from tiramisueanne/master
Fix incorrect comparison in Array.hh.
Thanks to tiramisueanne for the contribution
* Fix incorrect comparison in Array.hh
* Merge pull request #7 <https://github.com/LCAS/QuadProgpp/issues/7> from yuki-koyama/remove-unused-variable-warnings
Remove an unused variable declaration
* Merge pull request #8 <https://github.com/LCAS/QuadProgpp/issues/8> from …
```

quadprogpp: 0.0.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `quadprogpp` to `0.0.2-1`:
- upstream repository: https://github.com/LCAS/QuadProgpp.git
- release repository: https://github.com/lcas-releases/quadprogpp.git
```
* made comileable via catkin
* Merge pull request #12 <https://github.com/LCAS/QuadProgpp/issues/12> from tiramisueanne/master
Fix incorrect comparison in Array.hh.
Thanks to tiramisueanne for the contribution
* Fix incorrect comparison in Array.hh
* Merge pull request #7 <https://github.com/LCAS/QuadProgpp/issues/7> from yuki-koyama/remove-unused-variable-warnings
Remove an unused variable declaration
* Merge pull request #8 <https://github.com/LCAS/QuadProgpp/issues/8> from …
```

quadprogpp: 0.0.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.5.3-1`:
- previous version for package: `0.5.2-1`
```
* disable actor collisions
```
```
* Merge pull request #46 <https://github.com/LCAS/CMP9767M/issues/46> from gpdas/tutorial12_fixes
Merging this. minor changes.
* remapping some topics
* Contributors: Gautham P Das, gpdas
```

uol_cmp9767m: 0.5.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_perception_people` to `1.9.0-1`:
- previous version for package: `1.8.1-1`
```
* Merge pull request #226 <https://github.com/strands-project/strands_perception_people/issues/226> from semeyerz/people-check
readd people to subscription check
* readd people to subscription check
* Contributors: Christian Dondrup, Sebastian M. z. Borgsen
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Frame_id fix (#228 …
```

strands_perception_people: 1.9.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `1.0.0-1`:
- No changes
```
* added blockly
* fixed re
* added server files
```
- No changes
```
* working towards new assessment with maze (#34 <https://github.com/LCAS/teaching/issues/34>)
* added gzmaze editor
* updated gzmaze
* added build_depends
* simple lanuch and maze world
* changes for week 1 tutoral
* correct collisions
* Merge pull request #33 <https://github.com/LCAS/teaching/issues/33> from paul-baxter/kinetic
* minor position change …
```

lcas_teaching: 1.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `1.0.1-1`:
- No changes
- No changes
- No changes
```
* update gzmaze
```

lcas_teaching: 1.0.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `1.0.2-1`:
- previous version for package: `1.0.1-1`
- No changes
- No changes
- No changes
```
* gzmaze fixes and better default camera and light
```

lcas_teaching: 1.0.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `1.0.3-1`:
- previous version for package: `1.0.2-1`
- No changes
- No changes
- No changes
```
* updated gzmaze
```

lcas_teaching: 1.0.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_perception_people` to `1.10.0-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_perception_people: 1.10.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_executive` to `1.2.5-1`:
```
* Merge pull request #311 <https://github.com/strands-project/strands_executive/issues/311> from strands-project/ori-kinetic-devel
Merges in ORI developments from elsewhere
* Merge remote-tracking branch 'ori/kinetic-devel' into working-kinetic-devel
Adding in ori developments from last few months.
* Merge branch 'kinetic-devel' of https://github.com/strands-project/strands_executive into kinetic-devel
* big code clean: remove old …
```

strands_executive: 1.2.5-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `gazebo_contact_monitor` to `1.2.0-1`:
- upstream repository: https://github.com/LCAS/gazebo-contactMonitor.git
- release repository: https://github.com/lcas-releases/gazebo-contactMonitor.git
```
* Merge pull request #3 <https://github.com/LCAS/gazebo-contactMonitor/issues/3> from gpdas/melodic-devel
gazebo8-* -> gazebo-*
* gazebo8-* -> gazebo-*
* Corrected wrong param name. Added params as args.
* Contributors: Gautham P Das, Manuel Fernandez-Carmona, gpdas
```

gazebo_contact_monitor: 1.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `gazebo_contact_monitor` to `1.2.1-1`:
- upstream repository: https://github.com/LCAS/gazebo-contactMonitor.git
- release repository: https://github.com/lcas-releases/gazebo-contactMonitor.git
- previous version for package: `1.2.0-1`
```
* typo (#4 <https://github.com/LCAS/gazebo-contactMonitor/issues/4>)
* typo
* gazebo_ros
* proper flags for gazebo
* Contributors: Gautham P Das, Marc Hanheide
```

gazebo_contact_monitor: 1.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sentor` to `2.0.4-1`:
- previous version for package: `2.0.3-0`
```
* Merge pull request #8 <https://github.com/LCAS/sentor/issues/8> from adambinch/sentor_devel
New top-level arg lambdas_when_published that ensures that lambda e…
* Simplified code a little. Small change to the readme.
* Made latest changes thread safe.
* updated readme
* Fix
* New top-level arg lambdas_when_published that ensures that lambda expressions
can be satisfied only when the topic is being published.
* Merge pull request #7 <https://github.com/LCAS/sentor/issues/7> from …
```

sentor: 2.0.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `1.0.4-1`:
- previous version for package: `1.0.3-1`
- No changes
- No changes
- No changes
```
* Adding 3 mazes for testing the assignment (#36 <https://github.com/LCAS/teaching/issues/36>)
* WIP: new mazes and example solution
* not here
* 3 mazes and lanuch files
* fixed the models (removed state)
* fixing position of blue markers
Co-authored-by: Marc Hanheide <mailto:marc@hanheide.net>
* new color marker
* added missing dep
* added missing dep
* added missing dep …
```

lcas_teaching: 1.0.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.3.2-1`:
- previous version for package: `0.3.1-1`
```
* When planning considering also now obstacles obtained from the costmap
```

iliad_smp: 0.3.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `1.0.5-1`:
- previous version for package: `1.0.4-1`
- No changes
- No changes
- No changes
```
* configure fov and no range restriction (#37 <https://github.com/LCAS/teaching/issues/37>)
* configure fov and no range restriction
* changed close cut-off to not hit base
* wip
* scan range
```

lcas_teaching: 1.0.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_catkin_c11` to `1.8.3-1`:
```
* Merge pull request #1 <https://github.com/LCAS/pcl_catkin/issues/1> from LCAS/submodule
attempt to build as subdir
* attempt to build as subdir
* Contributors: Marc Hanheide, root
```

pcl_catkin_c11: 1.8.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `pcl_conversions_c11` to `0.2.3-1`:
- upstream repository: https://github.com/LCAS/pcl_conversions.git
- release repository: https://github.com/lcas-releases/pcl_conversions.git
```
```

pcl_conversions_c11: 0.2.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `perception_pcl_c11` to `1.4.6-1`:
- upstream repository: https://github.com/LCAS/perception_pcl.git
- release repository: https://github.com/lcas-releases/perception_pcl_c11.git
```
* added deps
* Contributors: root
```
- No changes

perception_pcl_c11: 1.4.6-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `franka_ros_lcas` to `0.8.0-1`:
- upstream repository: https://github.com/LCAS/franka_ros.git
- release repository: https://github.com/lcas-releases/franka_ros.git

franka_ros_lcas: 0.8.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.0.2-1`:
```
* Merge pull request #5 <https://github.com/SAGARobotics/AgriNav/issues/5> from Jailander/master
Preparing Release
* 0.0.1
* adding changelog
* Merge pull request #4 <https://github.com/SAGARobotics/AgriNav/issues/4> from Jailander/master
adding nav_msgs as a build dependency
* adding nav_msgs as a build dependency
* Merge pull request #3 <https://github.com/SAGARobotics/AgriNav/issues/3> from Jailander/master
Moving Polytunnel navigation actions to SAGARobotics …
```

saga_agrinav: 0.0.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.0.2-1`:
```
* Merge pull request #5 <https://github.com/SAGARobotics/AgriNav/issues/5> from Jailander/master
Preparing Release
* 0.0.1
* adding changelog
* Merge pull request #4 <https://github.com/SAGARobotics/AgriNav/issues/4> from Jailander/master
adding nav_msgs as a build dependency
* adding nav_msgs as a build dependency
* Merge pull request #3 <https://github.com/SAGARobotics/AgriNav/issues/3> from Jailander/master
Moving Polytunnel navigation actions to SAGARobotics …
```

saga_agrinav: 0.0.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `image_to_v4l2loopback` to `0.1.1-1`:
- upstream repository: https://github.com/LCAS/image_to_v4l2loopback.git
- release repository: https://github.com/lcas-releases/image_to_v4l2loopback.git
```
* new maintainer and install targets
* roslint in travis
* Building 16.04
* Image transport install
* Need cv bridge
* Updating travis yml
* Changing member variable naming convention
* Now using the latest v4l2loopback source, this node is working again which resolves #3 <https://github.com/LCAS/image_to_v4l2loopback/issues/3>
* Try getting format first, now it is clear where the issue is- may have to fix v4l2loopback itself
* …
```

image_to_v4l2loopback: 0.1.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `depth_sensors` to `0.1.0-1`:
```
* Removed dep from Turtlebot and added meshes here
* Contributors: Riccardo
```
- No changes
```
* added pi constant
```
- No changes
```
* Small fix for xacro
* Contributors: Riccardo
```
- No changes
```
* Small fix for xacro
* Contributors: Riccardo
```

depth_sensors: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `tradr_uol` to `1.1.0-1`:
- No changes
- No changes
```
* Move to Melodic [removed ref to vrep simulation]
* Contributors: pulver
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

tradr_uol: 1.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `image_to_v4l2loopback` to `0.1.2-1`:
- upstream repository: https://github.com/LCAS/image_to_v4l2loopback.git
- release repository: https://github.com/lcas-releases/image_to_v4l2loopback.git
- previous version for package: `0.1.1-1`
```
* TRAGETS
```

image_to_v4l2loopback: 0.1.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.0.3-1`:
- previous version for package: `0.0.2-1`
```
* Merge pull request #7 <https://github.com/SAGARobotics/AgriNav/issues/7> from Jailander/force_direction
Adds reconfigurable parameters to force the robot's direction
* Merge pull request #6 <https://github.com/SAGARobotics/AgriNav/issues/6> from Jailander/master
adding Missing files into the right repo
* Adds reconfigurable parameters to force the robot to go in a specific direction this are to be used with extreme caution
* adding Missing files into the right repo …
```

saga_agrinav: 0.0.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `1.1.1-1`:
```
* Merge pull request #6 <https://github.com/LCAS/topological_navigation/issues/6> from Jailander/master
Choosing move base action to approach node position following actions…
* Choosing move base action to approach node position following actions order defined in move_base_actions parameter.
This is very useful to establish priorities across the map
* Merge pull request #5 <https://github.com/LCAS/topological_navigation/issues/5> from …
```

topological_navigation: 1.1.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `2.0.0-1`:
- previous version for package: `1.1.1-1`
- No changes
- No changes

topological_navigation: 2.0.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `1.2.0-1`:
- previous version for package: `1.1.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_navigation: 1.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `2.0.0-1`:
- previous version for package: `1.0.8-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_navigation: 2.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `strands_navigation` to `2.0.0-1`:
- previous version for package: `1.2.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

strands_navigation: 2.0.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `sentor` to `2.1.0-1`:
- previous version for package: `2.0.4-1`
```
* Merge pull request #11 <https://github.com/LCAS/sentor/issues/11> from adambinch/sentor_devel
A significant change to the way sentor executes processes, and how args are specified in the config.
* The format of the config is now backwards compatible
(sentor can handle two formats for the signal when condition).
The lindsey config has been reverted back to the previous version.
* A few minor improvements
* No longer using separate timers to handle critical and non-critical lambda …
```

sentor: 2.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `sentor` to `2.1.0-1`:
- previous version for package: `2.0.3-1`
```
* Merge pull request #11 <https://github.com/LCAS/sentor/issues/11> from adambinch/sentor_devel
A significant change to the way sentor executes processes, and how args are specified in the config.
* The format of the config is now backwards compatible
(sentor can handle two formats for the signal when condition).
The lindsey config has been reverted back to the previous version.
* A few minor improvements
* No longer using separate timers to handle critical and non-critical lambda …
```

sentor: 2.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `2.1.0-1`:
- previous version for package: `2.0.0-1`
```
* Merge pull request #7 <https://github.com/LCAS/topological_navigation/issues/7> from heuristicus/improve-manager
Minor quality of life improvements for map_manager
* influence vertices generated by function rather than hardcoded
* goal tolerances are object attribute, close_nodes dist is a parameter
* add message_generation to cmakelists
* Contributors: Jaime Pulido Fentanes, Michal Staniaszek
```
```
* Merge pull request #8 …
```

topological_navigation: 2.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `2.1.0-1`:
```
* Merge pull request #7 <https://github.com/LCAS/topological_navigation/issues/7> from heuristicus/improve-manager
Minor quality of life improvements for map_manager
* influence vertices generated by function rather than hardcoded
* goal tolerances are object attribute, close_nodes dist is a parameter
* add message_generation to cmakelists
* Contributors: Jaime Pulido Fentanes, Michal Staniaszek
```
```
* Merge pull request #8 …
```

topological_navigation: 2.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.0.4-1`:
```
* Enable start_database.launch to use system mongo for CI and tests
```

topic_store: 0.0.4-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.0.5-1`:
- previous version for package: `0.0.4-1`
```
* Reduced required TQDM version
```

topic_store: 0.0.5-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `roboticsgroup_gazebo_plugins` to `0.0.2-1`:
- upstream repository: https://github.com/LCAS/roboticsgroup_gazebo_plugins.git
- release repository: https://github.com/lcas-releases/roboticsgroup_gazebo_plugins.git
```
* changed maintainers
* Merge pull request #14 <https://github.com/LCAS/roboticsgroup_gazebo_plugins/issues/14> from roboticsgroup/pid_ns
Add option to change the namespace of the pid
* Add option to change the namespace of the pid
* Merge pull request #13 <https://github.com/LCAS/roboticsgroup_gazebo_plugins/issues/13> from roboticsgroup/parameters
Update parameters
* Update parameters
* Default max effort to limit from sdf …
```

roboticsgroup_gazebo_plugins: 0.0.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.1.0-1`:
- previous version for package: `0.0.3-1`
```
* Merge pull request #19 <https://github.com/SAGARobotics/AgriNav/issues/19> from Jailander/dyn-error-handling
Better Dynamic reconfigure error handling
* Better Dynamic reconfigure error handling
* Merge pull request #17 <https://github.com/SAGARobotics/AgriNav/issues/17> from adambinch/install_target
Added row_detector_vis.py as an install target in cmakelists,
* Added row_detector_vis.py as an install target in cmakelists,
in order to address …
```

saga_agrinav: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.6.0-1`:
```
* Merge pull request #55 <https://github.com/LCAS/CMP9767M/issues/55> from LCAS/melodic-devel
Melodic devel
* thorvald tf_prefix must have a / at tail end (#51 <https://github.com/LCAS/CMP9767M/issues/51>)
* thorvald tf_prefix must have a / at tail end
* gazebo model hook fix
* re-enabling kinect2
* Merge branch 'master' into melodic-devel
* fix gazebo model path hook (#54 <https://github.com/LCAS/CMP9767M/issues/54>)
minor fix to GAZEBO_MODEL_PATH env hook.
* New world and …
```

uol_cmp9767m: 0.6.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `librealsense2_framos` to `2.29.1-1`:
- upstream repository: https://github.com/LCAS/librealsense.git
- release repository: https://github.com/lcas-releases/librealsense_framos.git

librealsense2_framos: 2.29.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `librealsense2_framos` to `2.29.2-1`:
- upstream repository: https://github.com/LCAS/librealsense.git
- release repository: https://github.com/lcas-releases/librealsense_framos.git
- previous version for package: `2.29.1-1`

librealsense2_framos: 2.29.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_framos_ros` to `3.0.0-1`:
```
* added dependency and maintainer
* changed to correct libs
* renaming complete, compiles
* renamed dirs
* Add eigen dependency - missing for Melodic. Contributors: Antoine Hoarau
```
```
* renaming complete, compiles
* renamed dirs
```

realsense_framos_ros: 3.0.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_framos_ros` to `3.0.1-1`:
- previous version for package: `3.0.0-1`
```
* handle config file correctly
```
```
```

realsense_framos_ros: 3.0.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_framos_ros` to `3.0.2-1`:
- previous version for package: `3.0.1-1`
```
* corrected path to default config file
```
- No changes

realsense_framos_ros: 3.0.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ndt_tools` to `2.0.3-1`:
- upstream repository: https://gitsvn-nt.oru.se/software/ndt_tools.git
- release repository: https://gitsvn-nt.oru.se/iliad/software/releases/ndt_tools-release.git
- previous version for package: `2.0.2-1`
```
* malcolm: missing dependencies+corrected string
I've added missing dependencies in ndt_feature_finder and ndt_offline
Furthermore, I've corrected on string_cxx11 by changing it to std.string
* Contributors: Malcolm Mielle
```
```
* malcolm: missing dependencies+corrected string
I've added missing dependencies in ndt_feature_finder and ndt_offline
Furthermore, I've corrected on string_cxx11 by changing it to std.string
* Contributors: Malcolm …
```

ndt_tools: 2.0.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_gazebo_plugin` to `0.1.0-1`:
- upstream repository: https://github.com/LCAS/realsense_gazebo_plugin.git
- release repository: https://github.com/lcas-releases/realsense_gazebo_plugin.git
- previous version for package: `0.0.1-1`
```
* Merge pull request #1 <https://github.com/LCAS/realsense_gazebo_plugin/issues/1> from Melanoneiro/master
Add Registered Depth Stream
* fix: Remove necessity of having registered depth cam enabling backwards compatibiliy
* feat: Add registered depth stream
* Contributors: Marc Hanheide, Nikolaus Wagner
```

realsense_gazebo_plugin: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.0.6-1`:
- previous version for package: `0.0.5-1`
```
* Updated requirements.txt
* Remove README.md typo
* Ensure rospy is initialised in convert.py script
```

topic_store: 0.0.6-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_lcas` to `0.0.1-1`:
```
* renamed file
* changed to cmp9767m base
* removed outdated deps
* removed outdated deps
* version
* initial commit
```

bacchus_lcas: 0.0.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.0.7-1`:
- previous version for package: `0.0.6-1`
```
* Added verbose print to TopicStore objects (ROSType and Document Size)
* Force subscriber when data storage key starts with '/'
Otherwise if topics don't exist when data collection starts then the topics will never be subscribed to
```

topic_store: 0.0.7-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.0.9-1`:
- previous version for package: `0.0.7-1`
```
* Removed GridFS package.xml entry (included in pymongo)
```

topic_store: 0.0.9-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.1.0-1`:
- previous version for package: `0.0.9-1`
```
* Merge pull request #6 <https://github.com/RaymondKirk/topic_store/issues/6> from RaymondKirk/fix_for_msg_depth_bug
GridFS improvements and fix for nested permutations of (dict -> list -> object) such as TF messages
* Updated README to reflect recent changes
* Store original document and session ID in file meta of GridFS documents (for cleanup)
* Fix for incompatible parsing of a dict -> list -> dict -> etc type nests
Search depth first (takes much longer though) but …
```

topic_store: 0.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `librealsense2_framos` to `2.33.2-1`:
- upstream repository: https://github.com/LCAS/librealsense.git
- release repository: https://github.com/lcas-releases/librealsense_framos.git
- previous version for package: `2.29.2-1`
```
* Corrected URL
* Removed external maintainer
* Merge pull request #3 <https://github.com/LCAS/librealsense/issues/3> from nikostsagk/2.33-WIP
More renaming.
* More renaming.
* Add -framos suffix to binaries
* I don't know why I commented this
* add deps
* set hard paths
* added default path
* install udev in release mode
* changed name and added framos dependencies
* Copied over from FRAMOS deb package
* Contributors: Marc Hanheide, nikostsagk
```

librealsense2_framos: 2.33.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_framos_ros` to `3.0.2-2`:
- previous version for package: `3.0.2-1`
```
* corrected path to default config file
```
- No changes

realsense_framos_ros: 3.0.2-2 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `realsense_framos_ros` to `3.2.14-1`:
- previous version for package: `3.0.2-2`
```
* Merge pull request #5 <https://github.com/LCAS/realsense/issues/5> from LCAS/for_v2.33
imported from FRAMOS packages
* imported from FRAMOS packages
* added logging to show it's FRAMOS
```
```
* Merge pull request #5 <https://github.com/LCAS/realsense/issues/5> from LCAS/for_v2.33
imported from FRAMOS packages
* imported from FRAMOS packages
```

realsense_framos_ros: 3.2.14-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.0.11-1`:
- upstream repository: https://github.com/spencer-project/spencer_people_tracking.git
- bloom version: `0.9.8`
- previous version for package: `1.0.10-0`
```
* Use find_package(Eigen3) instead of find_package(Eigen)
```
```
* Merge pull request #81 <https://github.com/spencer-project/spencer_people_tracking/issues/81> from LCAS/master
Changelog updates from LCAS buildfarm
```
```
* Various smaller fixes for ROS Kinetic
- Fix build warnings in laser_features and rwth_ground_plane
- Configurable odom and base footprint frame IDs …
```

spencer_people_tracking: 1.0.11-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_store` to `0.1.1-1`:
- bloom version: `0.9.8`
- previous version for package: `0.1.0-1`
```
* Merge pull request #7 <https://github.com/RaymondKirk/topic_store/issues/7> from RaymondKirk/add_action_server_video
Added ability to collect sequences with the action server
* Added ability to collect sequences with the action server
* Contributors: Raymond Tunstill (Kirk), RaymondKirk
```

topic_store: 0.1.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `spencer_people_tracking` to `1.2.1-1`:
- upstream repository: https://github.com/spencer-project/spencer_people_tracking.git
- bloom version: `0.9.8`
- previous version for package: `1.2.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix Qt5 cmake module not being found
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No …

spencer_people_tracking: 1.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `2.0.0-1`:
- bloom version: `0.9.8`
- previous version for package: `1.3.2-1`
```
* melodic-1.3.2
* changelogs
* melodic-1.3.1
* changelogs
* melodic-1.3.0
* changelog
```
```
* melodic-1.3.2
* changelogs
* Merge pull request #111 <https://github.com/SAGARobotics/Thorvald/issues/111> from MikHut/melodic-devel
tf_prefix fix same as #109 <https://github.com/SAGARobotics/Thorvald/issues/109> but for melodic-devel
* merge conflicts
* melodic-1.3.1
* changelogs
* melodic-1.3.0
* changelog
* Contributors: Jaime Pulido Fentanes, Marc …
```

thorvald: 2.0.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_lcas` to `0.2.0-1`:
- previous version for package: `0.0.1-1`
```
* Merge pull request #6 <https://github.com/LCAS/bacchus_lcas/issues/6> from LCAS/better_download_models
Better build and demo
* improved the download build and also allow rviz navigation
```
```
* Merge pull request #6 <https://github.com/LCAS/bacchus_lcas/issues/6> from LCAS/better_download_models
Better build and demo
* improved the download build and also allow rviz navigation
* Merge branch 'master' into …
```

bacchus_lcas: 0.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_lcas` to `0.2.1-1`:
- previous version for package: `0.2.0-1`
```
* fix deps
```
```
* fix deps
```

bacchus_lcas: 0.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_lcas` to `0.2.2-1`:
- previous version for package: `0.2.1-1`
```
* added exec_depend for launch files
```
- No changes

bacchus_lcas: 0.2.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `2.2.0-1`:
- previous version for package: `2.1.0-1`
```
* Merge pull request #48 <https://github.com/LCAS/topological_navigation/issues/48> from Jailander/new-pkg-version
Making package version number compatible with other packages for release
* Making package version number compatible with other packages for release
* Merge pull request #43 <https://github.com/LCAS/topological_navigation/issues/43> from francescodelduchetto/master
Topological localization package
* …
```

topological_navigation: 2.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `lcas_teaching` to `3.0.1-1`:

lcas_teaching: 3.0.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.3.3-1`:
- previous version for package: `0.3.2-1`
```
* CLiFF with PRM*
```

iliad_smp: 0.3.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.0.0-1`:
```
* 0.2.1
* changelog
* changed version number
* example now also has DynamicServer example
and further examples of qos and latch
* action server launch file is working
with prefix and dynamic server
* DynamicServer implementation working
* added launching own MQTT server
* removed
* intial actionlib mqtt setup
* support for latched (retained) topics and QoS
* ignore vscode
* fix install target for directories
```

mqtt_bridge_lcas: 1.0.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.0.1-1`:
```
* missing install target
* Merge branch 'pr_upstream' into melodic-devel
* example now also has DynamicServer example
and further examples of qos and latch
* action server launch file is working
with prefix and dynamic server
* DynamicServer implementation working
* added launching own MQTT server
* removed
* intial actionlib mqtt setup
* support for latched (retained) topics and QoS
```

mqtt_bridge_lcas: 1.0.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.1.0-1`:
- previous version for package: `1.0.1-1`
```
* Merge pull request #1 <https://github.com/LCAS/mqtt_bridge/issues/1> from LCAS/remoteserver
Remoteserver implementation complete
* implementation of RemoteServer working
* WIP: towards a remote server call
```

mqtt_bridge_lcas: 1.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.2.0-1`:
- previous version for package: `1.1.0-1`
```
* added LocalServiceProxy
* renamed to RemoteService
```

mqtt_bridge_lcas: 1.2.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.2.0-1`:
```
* added LocalServiceProxy
* renamed to RemoteService
```

mqtt_bridge_lcas: 1.2.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `uol_cmp9767m` to `0.6.1-1`:
- bloom version: `0.10.1`
- previous version for package: `0.6.0-1`
- No changes
```
* Merge pull request #60 <https://github.com/LCAS/CMP9767M/issues/60> from gcielniak/master
Corrected cmake file configuration for its use with actionlib
* Merge pull request #3 <https://github.com/LCAS/CMP9767M/issues/3> from gcielniak/work9_actions
missing actionlib_msgs in CMakeLists.txt
* missing actionlib_msgs in CMakeLists.txt
* Merge pull request #59 <https://github.com/LCAS/CMP9767M/issues/59> from gcielniak/master
additional rviz config files
* Merge pull …
```

uol_cmp9767m: 0.6.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.2.1-1`:
- bloom version: `0.10.1`
- previous version for package: `1.2.0-1`
```
* Merge pull request #2 <https://github.com/LCAS/mqtt_bridge/issues/2> from francescodelduchetto/avoid-loops
Avoid loops in connection with the server
* do not start a new bridge in the Server if the bridge with the reverse connection is already running bcs it create loops in ros messages
* improved documentation
```

mqtt_bridge_lcas: 1.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.2.2-1`:
- bloom version: `0.10.1`
- previous version for package: `1.2.1-1`
```
* Merge pull request #4 <https://github.com/LCAS/mqtt_bridge/issues/4> from LCAS/futures
simple threading solution
* simple threading solution
```

mqtt_bridge_lcas: 1.2.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `2.0.0-1`:
- bloom version: `0.10.2`
```
* Changes
* Add new cost function.
* Add WHyTeMapClient similar to others
* fix
* Fix bugs and add WHyTeMapServer for ROS
* Add conversion from msg to data struct and vice versa
* Add messages
* Vectorize likelihood computations
* Changes to WHyTe-map data structures
* Clang-format fix
* Add WHyTeMap. Code compiles on Ubuntu 18.04
```

mod_ros: 2.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `3.0.0-1`:
- bloom version: `0.10.2`
- previous version for package: `2.0.0-1`

mod_ros: 3.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `2.0.0-1`:
- bloom version: `0.10.2`
```
* Fix GMMT-map cost function errors
* Correct STeF-map upstream cost fn
* Small change
* Adding mixing factor to some cost objectives
* use parameter instead of constant value
* Update DTCOptimizationObjective.cpp
Update secondary cap.
* Add threshold to mahalanobis distance
* Change
* Add a std::shared_ptr typedef
* Many changes
* Add methods to compute cost components
* Remove reverse cost
* Fix description
* Add Down-The-WHyTe OO and add …
```

ompl_planners: 2.0.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `3.0.1-1`:
- bloom version: `0.10.3`
- previous version for package: `3.0.0-1`

mod_ros: 3.0.1-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.0-1`:
- bloom version: `0.10.3`
- previous version for package: `0.3.3-1`
```
* Including also stefmap and gmmtmap as MoDs
```

iliad_smp: 0.4.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `ompl_planners` to `2.1.0-1`:
- previous version for package: `2.0.0-1`
- No changes
```
* Changes to stefmap_ros objective
```

ompl_planners: 2.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `3.1.0-1`:
- previous version for package: `3.0.1-1`
- No changes
- No changes
```
* Changes merged in hard... from Sergi
```
- No changes
- No changes
```
* Changes merged in hard... from Sergi
* Add new launch files
```
- No changes
- No changes

mod_ros: 3.1.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `3.1.2-1`:
- previous version for package: `3.1.1-1`
```
* Merge branch 'master' of https://github.com/ksatyaki/mod_ros
* Add back atc data
```
```
* Merge branch 'master' of https://github.com/ksatyaki/mod_ros
```
```
* New ATC histograms and fix GMMT client and some stefmap scripts
* Merge branch 'master' of https://github.com/ksatyaki/mod_ros
```
``` …
```

mod_ros: 3.1.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `3.1.3-2`:
- previous version for package: `3.1.2-1`
```
* 3.1.2
* Changelogs updated
* Merge branch 'master' of https://github.com/ksatyaki/mod_ros
* Add back atc data
* 3.1.1
* Updated changelogs
* 3.1.0
* Updated changelogs
* 3.0.1
* 3.0.0
* 2.1.0
* Updated Changelogs
* 2.0.0
* don't print warning
* Add conversion from msg to data struct and vice versa
* Changes to WHyTe-map data structures
* updated cliffmpa launch files and stefmap data and scripts
* Contributors: Chittaranjan S Srinivas, Chittaranjan …
```

mod_ros: 3.1.3-2 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.2-1`:
- previous version for package: `0.4.0-1`
```
* Adjusting resolution of the planner for collision checking
```

iliad_smp: 0.4.2-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.3-1`:
- previous version for package: `0.4.2-1`
```
* iliad_smp is always now planning with two planners. The shorter one will be selected. The planners are selected via parameters.
```

iliad_smp: 0.4.3-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.4-1`:
- previous version for package: `0.4.3-1`
```
* Returning state lattice result as last resort
```

iliad_smp: 0.4.4-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `mod_ros` to `3.2.0-1`:
- previous version for package: `3.1.3-2`
```
* Fuix
* revert
* testing final chitt
* testing
* testing
* testing
* Changelogs added
* Merge branch 'master' of github.com:ksatyaki/mod_ros
* intermediate commit
* 3.1.3
* updated changelog
* 3.1.2
* Changelogs updated
* Merge branch 'master' of https://github.com/ksatyaki/mod_ros
* Add back atc data
* Contributors: Chittaranjan S Srinivas, Chittaranjan Swaminathan
* Merge branch 'master' of github.com:ksatyaki/mod_ros
* intermediate commit
* 3.1.3
* …
```

mod_ros: 3.2.0-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.5-1`:
- previous version for package: `0.4.4-1`
```
* Weight for OMPL resolution. LETHAL costs for obstacles coming from service GetPath. Locking the costmap until planning is finished.
```

iliad_smp: 0.4.5-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.6-1`:
- previous version for package: `0.4.5-1`
```
* Saving costmap in a file
```

iliad_smp: 0.4.6-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

kinetic/lcas-dist.yaml

Increasing version of package(s) in repository `iliad_smp` to `0.4.7-1`:
- previous version for package: `0.4.6-1`
```
* Using CForest instead of RRTstar. Simple logic to return state_lattice
```

iliad_smp: 0.4.7-1 in 'kinetic/lcas-dist.yaml' [bloom]

---

lcas-rosdistro-setup.sh

Just a minor change to the setup script. The script was failing because `pip install -U tmule` was trying to get the most recent version of web.py, which [has issues with python 2](https://forum.iredmail.org/post75845.html#p75845). I changed it to use the working version of web.py and removed the `-U` parameter so it would not try to upgrade. I also added the `-H` parameter to `sudo` to mollify pip.

Fixed pip warning and web.py version issue

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `thorvald` to `2.1.0-1`:
- previous version for package: `2.0.0-1`
```
* Merge branch 'melodic-devel' of https://github.com/sagarobotics/Thorvald into unified_thorvald
* Contributors: Lars Grimstad
```
```
* Merge branch 'melodic-devel' of https://github.com/sagarobotics/Thorvald into unified_thorvald
* Contributors: Lars Grimstad
```
```
* Merge pull request #157 <https://github.com/SAGARobotics/Thorvald/issues/157> from MikHut/melodic-devel-tiger-merge
Hacky Melodic devel tiger merge
* Merge branch 'melodic-devel' into …
```

thorvald: 2.1.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `2.3.0-1`:
- previous version for package: `2.2.0-1`
```
* Merge branch 'master' of github.com:LCAS/topological_navigation into tmap_to_tmap2
* Merge pull request #82 <https://github.com/LCAS/topological_navigation/issues/82> from adambinch/fix_conflicts
Fix conflicts
* Merge branch 'master' of github.com:LCAS/topological_navigation into fix_conflicts
* Merge pull request #62 <https://github.com/LCAS/topological_navigation/issues/62> from francescodelduchetto/master
New features in …
```

topological_navigation: 2.3.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.2.1-1`:
- previous version for package: `0.2.0-1`
```
* Merge pull request #54 <https://github.com/SAGARobotics/AgriNav/issues/54> from adambinch/melodic-devel
Default pole positions arg is an empty string.
* Default pole positions arg is an empty string.
Such that the Agrinav repo does not depend on thorvald_uv_bringup.
* Contributors: Jaime Pulido Fentanes, adambinch
```

saga_agrinav: 0.2.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_teaching` to `0.3.0-1`:
- previous version for package: `0.2.2-1`
```
* Removed actor plugin
* Cleanup Robotnik reference
* Merge pull request #30 <https://github.com/LCAS/bacchus_lcas/issues/30> from LCAS/fix_digital_twin_sim
thorvald up and running - sherpa still pending (new pull request will be opened)
* fix issue with riseholme ground plane
* Add riseholme terrain model
Extract riseholme terrain model from the downloaded 3D models file
* Merge remote-tracking branch 'origin/fix_digital_twin_sim' into fix_digital_twin_sim
* correct …
```

bacchus_teaching: 0.3.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_teaching` to `0.3.1-1`:
- previous version for package: `0.3.0-1`
```
* change defaults (for teaching only)
* added smaller worlds for teaching
* removed sprayer
* Various fix (sensor frame, local costmap, enable/disable dt)
* Contributors: Marc Hanheide, Riccardo
```
```
* Various fix (sensor frame, local costmap, enable/disable dt)
* Contributors: Riccardo
```

bacchus_teaching: 0.3.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.2.2-1`:
- previous version for package: `0.2.1-1`
```
* Merge pull request #62 <https://github.com/SAGARobotics/AgriNav/issues/62> from SAGARobotics/magnucha-add-missing-toponav-dep
Add topological_navigation_msgs as a dependency
* Merge pull request #64 <https://github.com/SAGARobotics/AgriNav/issues/64> from adambinch/detector_map_switching_fix
detector map switching fix
* detector map switching fix
* Add topological_navigation_msgs as a dependency
* Merge pull request #57 …
```

saga_agrinav: 0.2.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.4.0-1`:
- previous version for package: `1.2.2-1`

mqtt_bridge_lcas: 1.4.0-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_teaching` to `0.3.2-2`:
- previous version for package: `0.3.2-1`
```
* Merge pull request #40 <https://github.com/LCAS/bacchus_lcas/issues/40> from LCAS/coarse_models
Added new world with the coarse meshes
* Delete semantic.xacro
This is not needed here
* Added new world with the coarse meshes
+ disable multi_sim + set the world default to the simplified models.
* Merge pull request #39 <https://github.com/LCAS/bacchus_lcas/issues/39> from pulver22/teaching-multisim
Added support for multisim robot and various fix on tf prefix
* Fix …
```

bacchus_teaching: 0.3.2-2 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_teaching` to `0.3.3-1`:
- previous version for package: `0.3.2-2`

bacchus_teaching: 0.3.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `swerve_steering_controller` to `0.0.1-1`:
- upstream repository: https://github.com/LCAS/swerve_steering_controller.git
- release repository: https://github.com/lcas-releases/swerve_steering_controller.git

swerve_steering_controller: 0.0.1-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `saga_agrinav` to `0.2.3-1`:
- previous version for package: `0.2.2-1`
```
* Merge pull request #70 <https://github.com/SAGARobotics/AgriNav/issues/70> from MikHut/python3-devel
make use_row_detector a dynamic param
* make use_row_detector a dynamic param
* Merge pull request #69 <https://github.com/SAGARobotics/AgriNav/issues/69> from MikHut/python3-devel
dont publish pole likelihood field if we are using map tiles
* dont publish pole likelihood field if we are using map tiles
* Merge pull request #67 …
```

saga_agrinav: 0.2.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `bacchus_teaching` to `0.3.4-1`:
- previous version for package: `0.3.3-1`
```
* Merge pull request #43 <https://github.com/LCAS/bacchus_lcas/issues/43> from gcielniak/teaching
fix global costmap parameters
* enable nav_map_yaml as a configurable parameter
* Enable non-paused sim + Fix depth camera_info topic
* Revert Niko's commit
* 'improve' the world ;)
* Contributors: Riccardo, Riccardo Polvara, gcielniak, nikostsagk
* Patched arg for move_base missing in hierarchical launch files
* Fix camera frame in camera_info topic
* Contributors: …
```

bacchus_teaching: 0.3.4-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `topic_compression` to `0.0.4-1`:
- upstream repository: https://github.com/LCAS/topic_compression
- release repository: https://github.com/lcas-releases/topic_compression.git
- previous version for package: `0.0.2-1`

topic_compression: 0.0.4-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.4.2-1`:
- previous version for package: `1.4.0-1`
```
* Merge pull request #17 <https://github.com/LCAS/mqtt_bridge/issues/17> from LCAS/bugfix_loggers
fixing missing function enable_loggers
* fixing missing function enable_loggers
* Contributors: Marc Hanheide, Your Name
```

mqtt_bridge_lcas: 1.4.2-1 in 'melodic/lcas-dist.yaml' [bloom]

---

melodic/lcas-dist.yaml

Increasing version of package(s) in repository `mqtt_bridge_lcas` to `1.4.3-1`:
- previous version for package: `1.4.2-1`
```
* Merge pull request #18 <https://github.com/LCAS/mqtt_bridge/issues/18> from LCAS/server_tweaks
initial trials to set mosquitto server config
* make the config file an argument (and fix some timing in test)
* documenting the frequency flag
* few more defaults for broker
* initial trials to set mosquitto server config
```

mqtt_bridge_lcas: 1.4.3-1 in 'melodic/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `3.0.1-1`:
```
* Merge pull request #160 <https://github.com/LCAS/topological_navigation/issues/160> from Iranaphor/humble-dev
ROS 2 / Humble - porting
* Centralising topological_navigation stack messages to msgs package. (+version number sync across packages to 3.0.0)
* Updates to Maintainers and Authors
* full build working for topological_utils
* Compilation of message files and restructuring heirarchy for ros2 compatibility
* initial work towards a working …
```

topological_navigation: 3.0.1-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `3.0.2-1`:
- previous version for package: `3.0.1-1`
- No changes
```
* Merge pull request #174 <https://github.com/LCAS/topological_navigation/issues/174> from Iranaphor/humble-dev-dependencies
removal of pip dependency
* removal of pip dependency
* Contributors: James R Heselden, Marc Hanheide
```
- No changes
- No changes

topological_navigation: 3.0.2-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `3.0.3-1`:
- previous version for package: `3.0.2-1`
- No changes
- No changes
```
* missing dep
```
- No changes

topological_navigation: 3.0.3-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `sandbox` to `1.0.1-1`:
- upstream repository: https://github.com/LCAS/sandbox.git
- release repository: https://github.com/LCAS/sandbox-release.git
```
* trigger rebuild
* initial version
* initial version for humble
```

sandbox: 1.0.1-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `topological_navigation` to `3.0.5-1`:
- previous version for package: `3.0.4-1`
- No changes
```
* Merge pull request #178 <https://github.com/LCAS/topological_navigation/issues/178> from francescodelduchetto/humble-dev
Taking out  bayesian_topological_localisation
* removed msg not longer in this package
* removing bayesian_topological_localisation msg and srv definition
* Contributors: James Heselden, Marc Hanheide, francescodelduchetto
```
- No changes

topological_navigation: 3.0.5-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `libfranka_lcas` to `0.9.2-1`:
- upstream repository: https://github.com/LCAS/libfranka.git
- release repository: https://github.com/lcas-releases/libfranka_lcas.git

libfranka_lcas: 0.9.2-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `ugv_sdk_ros2` to `1.0.0-1`:
- upstream repository: https://github.com/LCAS/ugv_sdk.git
- release repository: https://github.com/lcas-releases/ugv_sdk.git
```
* swapped catking for ament
* [Release] bump verstion to 0.7.0
* Merge pull request #47 <https://github.com/LCAS/ugv_sdk/issues/47> from agilexrobotics/devel
support titan robot
* support titan robot
* Merge pull request #46 <https://github.com/LCAS/ugv_sdk/issues/46> from westonrobot/bugfix-scout_bms
src: fix scout bms feedback interface
* [Release] bump version to v0.6.0
* src: fix scout bms feedback interface
* Merge pull request #45 <https://github.com/LCAS/ugv_sdk/issues/45> from …
```

ugv_sdk_ros2: 1.0.0-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `ugv_sdk_ros2` to `1.0.1-1`:
- upstream repository: https://github.com/LCAS/ugv_sdk.git
- release repository: https://github.com/lcas-releases/ugv_sdk.git
```
* new version
* asio is full depend
```

ugv_sdk_ros2: 1.0.1-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `hunter_ros2` to `0.0.2-1`:
- upstream repository: https://github.com/LCAS/hunter_ros2.git
- release repository: https://github.com/lcas-releases/hunter_ros2.git
```
* Merge pull request #2 <https://github.com/LCAS/hunter_ros2/issues/2> from LCAS/lcas_additions
Lcas additions
* added missing dependency
* Merge pull request #15 <https://github.com/LCAS/hunter_ros2/issues/15> from lagrangeluo/master
odom:inner_angle to central
* odom:inner_angle to central
* Merge pull request #14 <https://github.com/LCAS/hunter_ros2/issues/14> from lagrangeluo/master
steercmd to angular
* steercmd to angular
* Merge pull request #13 …
```

hunter_ros2: 0.0.2-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

Increasing version of package(s) in repository `kiss_icp` to `0.4.1-1`:
- upstream repository: https://github.com/LCAS/kiss-icp.git
- release repository: https://github.com/lcas-releases/kiss-icp.git
- bloom version: `0.12.0`
```
* dev-container
* Cleanup ROS package.xml and CMakeLists.txt (#337 <https://github.com/LCAS/kiss-icp/issues/337>)
Add missing system dependencies as wel
* Change target names (#327 <https://github.com/LCAS/kiss-icp/issues/327>)
* Change target names
* This can be reverted, but it is related
* Fix also tbb population
* MakeAvailable for the win
* Revert "This can be reverted, but it is related"
This reverts commit 59b5d21607e66883ad71fa6b3ad3463075515d4a.
* Refactor KissICP pipeline to …
```

kiss_icp: 0.4.1-1 in 'humble/lcas-dist.yaml' [bloom]

---

humble/lcas-dist.yaml

This PR introduces add new repositories to our ros humble distro:
1. costmap_converter  
2. decomp_ros  
3. gofar_navigation  
4. kindr_humble  
5. livox_laser_simulation_ros2  
6. livox_ros_driver2  
7. meshroom_CLI  
8. mqtt_ros2  
9. point_cloud_msg_wrapper 
10. rasberry_coordination
11. rviz_2d_overlay_plugins  
12. tinyspline_ros  
13. volumetric_viewpoint_planner

Update lcas-dist.yaml - adding more repos

---

humble/lcas-dist.yaml

This pull request includes a change to the `humble/lcas-dist.yaml` file. The change adds a new repository entry for `ros2_param_dumper`.
Repository addition:
* [`humble/lcas-dist.yaml`](diffhunk://#diff-4e961bc4f2fecde3b16b6f5f39f7a84367006c248a394cd15b3b3c70d0e90f0cR260-R265): Added `ros2_param_dumper` repository with its source details and status.

Add ros2_param_dumper repository to lcas-dist.yaml

---

scripts/rosdistro_analyser.py

This pull request includes a small change to the `scripts/rosdistro_analyser.py` file. The change re-enables the `--recurse-submodules` option in the `__checkout` method, which ensures that submodules are also cloned when cloning a repository.

recurse submodules

---

.github/workflows/build_cache.yaml
.github/workflows/build_test.yaml
.github/workflows/sync_upstream.yaml
rosdep/lcas.yaml

This pull request includes updates to workflows and dependency configurations to modernize the environment and add new package support.
* [`.github/workflows/build_cache.yaml`](diffhunk://#diff-efda2253b02690fece5ff7a9c7ea87703cde3aa47d9916db7768ecfb60e3d099L21-R21): Updated the `runs-on` field to use `ubuntu-22.04` instead of `ubuntu-20.04` for generating cache jobs.
* [`.github/workflows/build_test.yaml`](diffhunk://#diff-70770e65d5d7633e6d0f26ffd9a93b4b75dcc940311957eac1a717fdcbf1299dL15-R15): Updated the `runs-on` field to use `ubuntu-22.04` instead of `ubuntu-20.04` for testing jobs.
* [`rosdep/lcas.yaml`](diffhunk://#diff-2ce41dd072bfc0cc95aa9992f5bbcec6cf53b8771f41f02ef42f68cad151b8faR89-R92): Added support for the `python_mcp` package via pip under the `ubuntu` distribution.

Update build environment to Ubuntu 22.04 and add python_mcp dependency
